### ISSUE TITLE
Bug: Operator should successfully delete MySqlUser if KeyVault is not attached

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1142]
**Describe the bug**
When Creating a MySqlUser with no KeyVault connected, I am able to successfully delete a MySqlUser through the CLI, but the user is still showing up on the MySqlWorkbench

**To Reproduce**
Here is my yaml file which produced the above:

```
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLUser
metadata:
  name: mysqluser-sample-melrushnokyvk
spec:
  server: mysqlserver-sample-mel
  dbName: mysqldatabase-sample-mel
  resourceGroup: resourcegroupmeltest
  roles: 
  #now only supports to grant previleges to a new user, the previleges could be one or more of the below
  #SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, 
  #CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, 
  #CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
    - "select on *.*"
  # Specify a specific username for the user
  # username: mysqluser-sample-melrush
  # # Specify adminSecret and adminSecretKeyVault if you want to 
  # # read the MYSQL server admin creds from a specific keyvault secret
  # adminSecret: default-mysqlserver-sample-mel
  # adminSecretKeyVault: keyvaultsamplemelvin

  # Use the field below to optionally specify a different keyvault 
  # to store the secrets in
  # keyVaultToStoreSecrets: asokeyvault
```
I didn't set the values username, adminSecret, and adminSecretKeyVault.

**Expected behavior**
Able to successfully delete a MySql user if it does not have a keyvault attached

Also verify this bug doesn't exist on 
- PostgreSqlUser
- AzureSqlUser

If it does, handle the same way and allow successful delete

**Screenshots**
Here is my MySqlWorkbench with mysqluser-sample-mysqluser-sample-melrushnokyvk displaying after a delete:
![mysql](https://user-images.githubusercontent.com/7874406/83920869-63a63480-a73a-11ea-8712-3635c06d7732.png)

**Additional context**
