### ISSUE TITLE
Feature: Default ResourceGroup and Location to the location of the cluster (if it's deployed in Azure)

### ISSUE THREAD

**Issue by MarcPow** [Azure/azure-service-operator#1247]
Imagine that you have ~10 clusters, spread across ten different regions, where you want to deploy an instance of your service to each, in a location agnostic way.  Further imagine that this application requires custom, non-compute resources - SQL servers, Cosmos Dbs, Public IPs.

It would be excellent if you could deploy the same CRDs to every cluster, with your resources set to:
- Location: CLUSTER_LOCATION
- ResourceGroup: CLUSTER_RESOURCE_GROUP

And have it appropriately default.

This would have positive AuthN/AuthZ side effects as well, since the cluster already has an identity that allows it to manipulate resources in that group, I believe, without additional access grants.

Related to: #1237

**Comment by kyschouv** [comment]
As an alternative (and since configuration of operators in OLM seems difficult), it might work well to be able to define a `ResourceGroup` (and be able to import one that wouldn't be managed by ASO, just references), then be able to reference that (either by namespace/name or by selector) from other CRDs as the resource group (and default location) to deploy a resource to.

As an example, for a `BlobContainer`:

```yaml
apiVersion: azure.microsoft.com/v1alpha1
kind: BlobContainer
metadata:
  name: blobcontainer-sample
  namespace: blobsample
spec:
  resourcegroup:
    namespace: aso-defaults
    name: aso-default-rg
  accountname: storageaccountsample777
  # accessLevel - Specifies whether data in the container may be accessed publicly and the level of access.
  # Possible values include: 'Container', 'Blob', 'None'
  accesslevel: Container
```
