### ISSUE TITLE
Bug: PostgreSQLServer sample provided does not work

### ISSUE THREAD

**Issue by yashodhan10** [Azure/azure-service-operator#1325]
**Describe the bug**

The sample yaml file provided for PostgreSQLServer does not work. It errors out with an error:

Error from server: error when creating "serv.yaml": conversion webhook for azure.microsoft.com/v1alpha1, Kind=PostgreSQLServer failed: Post https://azureoperator-webhook-service.azureoperator-system.svc:443/convert?timeout=30s: dial tcp 10.0.96.217:443: connect: connection refused

Contents of serv.yaml:

``` yaml
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: postgreserver-sample
spec:
  location: eastus2
  resourceGroup:<RG_NAME>
  serverVersion: "11"
  sslEnforcement: Disabled
  createMode: Default
  sku:
    name: GP_Gen5_4
    tier: GeneralPurpose
    family: Gen5
    size: "51200"
    capacity: 4
```

**To Reproduce**

Install ASO and kubectl -f serv.yaml

**Expected behavior**

**Screenshots**

**Additional context**
