### ISSUE TITLE
Bug: MinLength validations on types aren't showing up on CRDs

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1337]
**Describe the bug**
There are 59 `kubebuilder:validation:MinLength` validation annotations on types under `api/`, but the generated CRDs in `config/crd/bases/` only have 4 occurences of `minLength` constraints in the schema. As an example, this code in `api/v1alpha1/cosmosdb_types.go`:
```go
type CosmosDBSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// +kubebuilder:validation:MinLength=0

	Location string `json:"location,omitempty"`
	// +kubebuilder:validation:Pattern=^[-\w\._\(\)]+$
	// +kubebuilder:validation:MinLength:1
	// +kubebuilder:validation:Required
	ResourceGroup          string                        `json:"resourceGroup"`
	Kind                   CosmosDBKind                  `json:"kind,omitempty"`
	Properties             CosmosDBProperties            `json:"properties,omitempty"`
	VirtualNetworkRules    *[]CosmosDBVirtualNetworkRule `json:"virtualNetworkRules,omitempty"`
	KeyVaultToStoreSecrets string                        `json:"keyVaultToStoreSecrets,omitempty"`
	Locations              *[]CosmosDBLocation           `json:"locations,omitempty"`
	IPRules                *[]string                     `json:"ipRules,omitempty"`
}
```
...results in these schema snippets:
```yaml
            location:
              minLength: 0
              type: string
...
            resourceGroup:
              pattern: ^[-\w\._\(\)]+$
              type: string
```

**Expected behavior**
The CRDs should have minLength set on all the fields that are marked with the annotation.
