### ISSUE TITLE
Improve how database users are modeled for MySQL and PostgreSQL

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1346]
**Describe the current behavior**
Our current Kubernetes object graph models database users at a per-database level across all supported database types. This has the advantage of allowing us to configure ownership so that if a user is created for a particular database (and both the user and database are being managed by ASO) then deleting the database will also delete the users in Kubernetes.

The downside of this though is that MySQL and PostgreSQL allow more flexible user management, where a single user may have permissions to many databases. While it's technically possible to have users with permissions to multiple databases in our current model it requires creating many ASO entities all pointing to the same database user. This is not recommended as the reconciliation for each entity will be in competition. Ownership is difficult as well in this model, as deleting one database should delete the user in Kubernetes assigned to that database, but _not actually delete the user in the database_ since there are other Kubernetes entities also referring to the same database user.

Even worse than the above: there are permissions which are _server_ level permissions and cannot be granted at the database level. We do not have a good way to model this currently.

**Describe the improvement**
Database users could be modelled more closely to how the various database products actually manage them, where really the user is at the server level and then is granted permissions to 1 or more databases. A CRD might look something like this:

```yaml
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLUser
metadata:
  name: mysqluser-sample
spec:
  server: mysqlserver-sample-777
  resourceGroup: resourcegroup-azure-operators
  roles:
    - "REPLICATION CLIENT"
    - "PROCESS"
  databaseRoles:
    mysqldatabase-sample:
      - "SELECT"
      - "INSERT"
      - "UPDATE"
      - "DELETE"
```

This has the following advantages:
1. Easily models what we currently allow.
2. Allows server level permissions.
3. Allows a single user (managed by a single entity in Kubernetes) to have permissions to multiple databases.

The main disadvantage of this approach is that if you want to delete the user entity in Kubernetes when the database is deleted you can no longer do that, as it would now be owned by the database server.

**Additional context**
This would be a **breaking change** and would (eventually) apply to PostgreSQL and MySQL database users, both AAD and normal "flavors" of user.
