### ISSUE TITLE
Bug: Incompatible with managed AAD pod identity

### ISSUE THREAD

**Issue by NillsF** [Azure/azure-service-operator#1381]
**Describe the bug**
There is no way to get ASO to work with AAD managed pod identity.
Reason:

1. ASO uses ```aadpodidbinding=aso_manager_binding```
2. ```az aks pod-identity create``` fails when the name of the pod-identity is ```aso_manager_binding```. This does however succeed using ```aso-manager-binding``` as pod-identity name.

**To Reproduce**
- Create AKS cluster using pod identity. Example:
```bash
az aks create -g rg-handsonaks -n handsonaks \
  --enable-managed-identity --enable-pod-identity \
  --network-plugin azure --node-vm-size Standard_DS2_v2 \
  --node-count 2 --generate-ssh-keys 
```

- Configure ASO, using this values.yaml:
```yaml
azureTenantID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
azureSubscriptionID: "d19dddf3-9520-4226-a313-ae8ee08675e5"
azureOperatorKeyvault: "handson-aks-aso"
azureClientID: "3a65e2ff-7831-4ed6-8922-7cf6a00d3698"

cloudEnvironment: AzurePublicCloud
azureUseMI: true
image:
  repository: mcr.microsoft.com/k8s/azureserviceoperator:0.1.16800
installAadPodIdentity: false

aad-pod-identity:
  azureIdentityBinding:
    name: aso-identity-binding
    selector: aso-identity-binding
  azureIdentity:
    enabled: True
    name: aso-identity
    type: 0
    resourceID: "/subscriptions/d19dddf3-9520-4226-a313-ae8ee08675e5/resourceGroups/ASO/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-mi"
    clientID: "3a65e2ff-7831-4ed6-8922-7cf6a00d3698"
```
- Install using
```
helm upgrade --install aso \
  azureserviceoperator/azure-service-operator \
  -n azureoperator-system --create-namespace \
  -f values.yaml
```
**Expected behavior**
It would be great if ASO would be compatible with the managed AAD pod identity add-on. I believe the easiest fix is the change the aadpodidbinding to aso-manager-binding. Maybe there's an option for the AAD pod managed identity add-on to accept identity names with an underscore in them.

**Further details**
- Adding the identity fails when the name contains an underscore
```bash
az aks pod-identity add --resource-group rg-handsonaks \
>   --cluster-name handsonaks --namespace azureoperator-system \
>   --name aso_manager_binding \
>   --identity-resource-id /subscriptions/d19dddf3-9520-4226-a313-ae8ee08675e5/resourceGroups/ASO/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-mi
```
![image](https://user-images.githubusercontent.com/6205923/107865459-728dcc80-6e1b-11eb-99ec-5690af5829e6.png)

**Comment by miwithro** [comment]
@bcho

**Comment by bcho** [comment]
Hi @NillsF , this is the expected behavior in managed pod identity addon. We use the pod identity name here as the kubernetes `AzureIdentity` resource's name, which means, the name has to use [DNS subdomain name pattern][kk_dns_subdomain_name]. Therefore, we cannot use/support underscore here. 

[kk_dns_subdomain_name]: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

**Comment by babbageclunk** [comment]
Ok - from some experimentation I can see that the `pod-identity add` command is creating both an AzureIdentity and an AzureIdentityBinding:
```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.azure.com/managedby: aks
  name: aso-manager-binding
  namespace: azureoperator-system
spec:
  clientID: <guid>
  resourceID: /subscriptions/<subscriptionid>/resourcegroups/<groupname>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my-managedidentity
  type: 0

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.azure.com/managedby: aks
  name: aso-manager-binding-binding
  namespace: azureoperator-system
spec:
  azureIdentity: aso-manager-binding
  selector: aso-manager-binding
```

@bcho, I can understand why the identity name can't have underscores but is there any way to control the selector on the binding independently of the identity name when it's created with the pod-identity command? That's the part that would need to be `aso_manager_binding` to match the binding on our pod definition.
