### ISSUE TITLE
Bug: blockOwnerDeletion fails with the operator

### ISSUE THREAD

**Issue by gorkem** [Azure/azure-service-operator#1385]
**Describe the bug**
On an OpenShift cluster, I have created a `PostgreSQLServer` fails the reconciler seems to never succeed. I see the following error on the events and similar ones on the controllers logs. 

```
* secrets "postgresqlserver-sample" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

**To Reproduce**

Here is the spec I have used for creating the CR.  
```
spec:
  createMode: Default
  location: eastus
  replicaProperties: {}
  resourceGroup: resourcegroup-azure-operators
  serverVersion: '10'
  sku:
    capacity: 4
    family: Gen5
    name: GP_Gen5_4
    size: '51200'
    tier: GeneralPurpose
  sslEnforcement: Enabled
```
**Expected behavior**
PostgreSQLServer provisioned

**Screenshots**

**Additional context**
