### ISSUE TITLE
Feature: Secrets created by ASO should have configurable annotations

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1398]
As originally requested in #1396, @EdYa was looking for a way to allow another namespace access to the secret created by a `PostgreSQLUser`.
>  I could imagine that annotation support for secrets could be quite helpful. If we could add some annotations for kubernetes-reflector then we could mirror the secrets to the correct namespace.

An example of what this might look like:
```
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: psqluser
spec:
  server: psqlserver
  dbName: psqldb
  resourceGroup: myrg
  secretConfig:
    metadata:
      annotations:
        my-annotation: "foo"
```

We have other fields which are often applicable for secrets as well, such as `KeyVaultToStoreSecrets`. It's possible that it would make sense to move this value into this `secretConfig` at some point in the future as well.
