### ISSUE TITLE
Discussion/investigation for OneOf improvements

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1515]
We want to support `oneOf` better. Here's an example of a JSON schema using `oneOf` (for an actual sample from an Azure service, see [this JSON schema](https://schema.management.azure.com/schemas/2019-04-01/Microsoft.Network.FrontDoor.json) and [this Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-04-01/frontdoor.json#L892)):

## Example OneOf JSON schema
```
{
    "Animal": {
        "type": "object",
        "oneOf": [
            {
                "$ref": "#/definitions/Cat"
            },
            {
                "$ref": "#/definitions/Dog"
            }
        ]
    },
    "Cat": {
        "type": "object",
        "properties": {
            "claws": {
                "type": "integer"
            }
        }
    },
    "Dog": {
        "type": "object",
        "properties": {
            "paws": {
                "type": "integer"
            }
        }
    }
}
```

Here's how we could render into Kubernetes CRDs with CRD API version `apiextensions.k8s.io/v1beta1` (skipping over how to do it in Kubebuilder for a second): 
```
        spec:
          oneOf:
            - type: object
              properties:
                claws:
                  type: integer
              required: ["claws"]
            - type: object
              properties:
                paws:
                  type: integer
              required: ["paws"]```
```

There is an issue though which is that, starting with Kubernetes CRD API version `v1` (which presumably we will want to target), Kubernetes doesn't actually support a full set of OpenAPI, it restricts things to what it calls the [structural schema](https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema). You can read more about structural schema [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md).

> A structural schema is an OpenAPI v3.0 validation schema which:
>
> 1. specifies a non-empty type (via type in OpenAPI) for the root, for each specified field of an object node (via properties or additionalProperties in OpenAPI) and for each item in an array node (via items in OpenAPI), with the exception of:
        a node with x-kubernetes-int-or-string: true
        a node with x-kubernetes-preserve-unknown-fields: true
> 2. for each field in an object and each item in an array which is specified within any of allOf, anyOf, oneOf or not, the schema also specifies the field/item outside of those logical junctors (compare example 1 and 2).
> 3. does not set description, type, default, additionalProperties, nullable within an allOf, anyOf, oneOf or not, with the exception of the two pattern for x-kubernetes-int-or-string: true (see below).

The major issue is item **number 2** - this basically means that you can't model `oneOf` exactly how it's modeled in ARM (or in OpenAPI in general).

Kubernetes has specific guidance with regard to discriminated unions and how they should be represented [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190325-unions.md), which effectively suggests that you define a single type with a property for each possible DU option and then enforce in the OpenAPI that exactly one property is specified. With my `CatDog` example above that would look like this in CRD-land:

## apiextensions.k8s.io/v1 supported CRD
```
        spec:
          properties:
            cat:
              type: object
              properties:
                claws:
                  type: integer
            dog:
              type: obect
              properties:
                paws:
                  type: integer
          oneOf:
            - required: ["cat"]
            - required: ["dog"]
          type: object
```

Some notes:
1. controller-gen doesn't give control over what the openapi schema of a given type is, we had found https://github.com/kubernetes/kube-openapi/tree/master/pkg/generators#custom-openapi-type-definitions but that only applies to kube-openapi (a different tool than controller-gen as far as I can tell).
2. There is some good discussion/examples in [this GitHub issue](https://github.com/kubernetes-sigs/controller-tools/pull/298) about how this would be supported in Kubebuilder - as far as I can tell, there currently is no support for generating CRDs with the Kubernetes suggested DU structure (1 property for each option, must fill exactly 1 property) using controller-gen - @devigned are you aware of this?

## Conclusion
This leaves us in a bit of an awkward situation:
1. We currently generate a Go type with `interface{}` for each type which is a `oneOf` - but `controller-gen` doesn't know what to do with `interface{}` and will error out on it if it's in one of our model types.
2. We can't just "do what the schema does" because Go doesn't support DUs directly, and Kubebuilder's generated CRDs don't support that either.
3. Kubernetes recommends against polymorphic types (including `oneOf`/`anyOf`) [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md#criteria) - see: "Note: we explicitly accept that polymorphic types (like IntOrString) are an anti-pattern for Kubernetes-like types and we do not want to encourage its use beyond IntOrString."

## Proposed solution
Given all of the above, I think we may need to take a path that turns [OneOf schemas](#Example-OneOf-JSON-schema) into Go types that fit the structural schema requirements. This is more inline with what Kubernetes wants CRDs to look like but means that we don't look _exactly_ like the ARM API.
For the linked schema that type would look like:
```
type Animal struct {
    Cat *Cat `json:"cat,omitempty"`
    Dog *Dog `json:"dog,omitempty"`
}

type Cat struct {
    Claws int `json:"claws"`
}

type Dog struct {
    Paws int `json:"paws"`
}
```
