### ISSUE TITLE
Bug: conversion webhook service not found

### ISSUE THREAD

**Issue by ramjigit** [Azure/azure-service-operator#1531]
**Describe the bug**
Error from server: error when creating "azuredb.yaml": conversion webhook for azure.microsoft.com/v1alpha1, Kind=AzureSqlDatabase failed: Post "https://webhook-service.system.svc:443/convert?timeout=30s": service "webhook-service" not found

**To Reproduce**
<Fill in the steps>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ramjigit** [comment]
Not able to create Azuresqlserver or DB ,getting webhook issue

**Comment by babbageclunk** [comment]
Hi @ramjigit, digging into it it looks to be a problem with our recent release - the webhook service and namespace should have been rewritten by `kustomize` to have the prefix `azureoperator-`. We're working on a fix at the moment.

**Comment by cpflaume** [comment]
I have a similar issue: When I run 'make manifests' or 'make install', the path for the webhook is not rewritten properly:

What is looks like
```yaml
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: xxx
        service:
          name: webhook-service
          namespace: system
```

What it did look like in the past or should look like

```yaml
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: xxx
        service:
          name: azureoperator-webhook-service
          namespace: azureoperator-system
          path: /convert
          port: 443
```
This currently blocks me to contribute to this project...
