### ISSUE TITLE
Bug: MySQLUser admin secret not found

### ISSUE THREAD

**Issue by nmeisenzahl** [Azure/azure-service-operator#1573]
**Describe the bug**
I'm trying to create a MySQL User in a MySQL database not managed by ASO. When I do so I'm getting the following error:
```
MySQLServer admin secret not found: secret "mysqlserver-default-mysql-admin-password"
    could not be found in KeyVault "https://my-akv.vault.azure.net": keyvault.BaseClient#GetSecret:
    Failure responding to request: StatusCode=404 -- Original Error: autorest/azure:
    Service returned an error. Status=404 Code="SecretNotFound" Message="A secret
    with (name/id) mysqlserver-default-mysql-admin-password was not found in this
    key vault.
```

I'm not sure why ASO tries to access "mysqlserver-default-mysql-admin-password" as the value in 'adminSecret' is different one.

Sample YAML:
``` yaml
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLUser
metadata:
  name: xxx
spec:
  adminSecret: mysql-admin-password
  adminSecretKeyVault: my-akv
  databaseRoles:
...
```

I'm also not totally sure which content the secret should provide. The docs do not mention this. Just the admin user password?

**To Reproduce**
1. Create a MySQL server (without ASO)
2. Create a MYSQL user with the above-mentioned yaml
