### ISSUE TITLE
Change EventHub CRD so that Attributes are Camelcase over Lowercase

### ISSUE THREAD

**Issue by JasonTheDeveloper** [Azure/azure-service-operator#159]
Right now the CRD for creating an event hub, all the custom attributes are lowercase. Would be better if they were camelcase instead.

Example:

```yaml
apiVersion: azure.microsoft.com/v1
kind: Eventhub
metadata:
  name: eventhub-sample-2307-09
spec:
  location: "westus"
  resourcegroup: "resourcegroup-sample-1907"
  namespace: "eventhubnamespace-sample-6"
  properties:
    messageretentionindays: 7
    partitioncount: 1
  authorizationrule: 
    name : "RootManageSharedAccessKey"
    rights: 
      - "Listen"
      - "Manage"
      - "Send"
  secretname: "secret-stream-eventhub-sample"
```

Should look like:

```yaml
apiVersion: azure.microsoft.com/v1
kind: Eventhub
metadata:
  name: eventhub-sample-2307-09
spec:
  location: "westus"
  resourceGroup: "resourcegroup-sample-1907"
  namespace: "eventhubnamespace-sample-6"
  properties:
    messageRetentionInDays: 7
    partitionCount: 1
  authorizationRule: 
    name : "RootManageSharedAccessKey"
    rights: 
      - "Listen"
      - "Manage"
      - "Send"
  secretName: "secret-stream-eventhub-sample"
```
