### ISSUE TITLE
Documentation of how to setup ignoreDifferences in Argo CD 

### ISSUE THREAD

**Issue by ErikLundJensen** [Azure/azure-service-operator#1604]
This is not a bug just some information if you are using Argo CD and azure-service-operator Helm chart.

The CRD field `spec.preserveUnknownFields` does not show when set to `true` in `apiextensions.k8s.io/v1` and Argo CD will therefore try to reconcile the CRD's in the azure-service-operator Helm Chart as it expects the field to visible.

To work around this we have to set the ignoreDifferences in Argo CD application.

Example of the syncPolicy from Argo CD `application` is shown below. 
```
spec:
  ...
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind:  ValidatingWebhookConfiguration      
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
    - group: apiextensions.k8s.io
      name: azureloadbalancers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azurenetworkinterfaces.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azurepublicipaddresses.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlactions.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqldatabases.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlfailovergroups.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlfirewallrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlmanagedusers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlservers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlusers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azuresqlvnetrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azurevirtualmachineextensions.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azurevirtualmachines.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: azurevmscalesets.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: apimgmtapis.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: apimservices.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: appinsights.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: appinsightsapikeys.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: blobcontainers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: consumergroups.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: cosmosdbs.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: cosmosdbsqldatabases.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: eventhubnamespaces.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: eventhubs.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: keyvaultkeys.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: keyvaults.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlaadusers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqldatabases.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlfirewallrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlserveradministrators.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlservers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlusers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: mysqlvnetrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: postgresqldatabases.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: postgresqlfirewallrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: postgresqlservers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: postgresqlusers.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: postgresqlvnetrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: rediscacheactions.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: rediscachefirewallrules.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: rediscaches.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: resourcegroups.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: storageaccounts.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: virtualnetworks.azure.microsoft.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields

```

Tags: argocd, azure-service-operator, crd
