### ISSUE TITLE
clientID is required! - Managed Identity

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-service-operator#1735]
**Describe the bug**

Current Setup Overview

K8s version AKS - 1.20.7

```
k version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

Use following command to create the cluster 

```
az aks create -g akscluster -n handsonaks --enable-managed-identity --enable-pod-identity --network-plugin azure --node-vm-size Standard_DS2_v2 --node-count 2 --generate-ssh-keys 
```

**To Reproduce**
- AKS cluster with Managed Identity.
- Create a managed Identity called aso-mi
- Add role assignment to aso-mi with the role Managed Identity Operator for (clustername)-nodepool managed identity
- Create Key Vault and assigned the access policy to managed identity aso-mi
- Give contributor access to aso-mi in the subscription RBAC

```
az aks pod-identity add --resource-group akscluster \
  --cluster-name handsonaks --namespace azureoperator-system \
  --name aso-identity-binding \
  --identity-resource-id  <managed identity resource ID>
```

```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```

```
helm repo add azureserviceoperator \
https://raw.githubusercontent.com/Azure/azure-service-operator/master/charts
```

```
azureTenantID: <Tenent-ID>
azureSubscriptionID: <Sub ID>
azureOperatorKeyvault: <Keyvault name>
azureClientID: <Manged Identity Client ID>


cloudEnvironment: AzurePublicCloud
azureUseMI: true
image:
  repository: mcr.microsoft.com/k8s/azureserviceoperator:0.1.16800
installAadPodIdentity: true

aad-pod-identity:
  azureIdentityBinding:
    name: aso-identity-binding
    selector: aso_manager_binding
  azureIdentity:
    enabled: True
    name: aso-mi
    type: 0
    resourceID: <Manged Identity resource ID>
    clientID: <Manged Identity Client ID>
```

<Fill in the steps>

**Expected behavior**

**Screenshots**
<img width="1166" alt="2021-08-24_00-21-19" src="https://user-images.githubusercontent.com/16514562/130501635-33c9cf9d-0b73-419c-ba0e-ed0d2954a952.png">

**Additional context**
