### ISSUE TITLE
unable to specify hostnames when creating MySQLAADUser using ASO

### ISSUE THREAD

**Issue by nickelodean** [Azure/azure-service-operator#1760]
**Describe the bug**

we use below yaml to provision azure database for mysql. In yaml,  If we give `username: mysqlaaduser ` , in db it creates as `'mysqlaaduser'@'%' ` , we want to get rid of the wild card for various security reasons,  we tried with `username: mysqlaaduser@101.245.%`   it created in db as `'mysqlaaduser'@'101.245.%'@'%' `   so username is being taken as `'mysqlaaduser'@'172.21.%'`  and hostname as `'%'`

is there an example of how to specify hostnames in yaml while provisioning..?

```
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLAADUser
metadata:
  name: mysqlaaduser
spec:
  resourceGroup: <resourcegroupname>
  server: <azuremysqlservername>
  aadId: "{{.DB_MANAGED_ID}}"
  username: mysqlaaduser
```

**To Reproduce**

```
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLAADUser
metadata:
  name: mysqlaaduser
spec:
  resourceGroup: <resourcegroupname>
  server: <azuremysqlservername>
  aadId: "{{.DB_MANAGED_ID}}"
  username: mysqlaaduser
```

**Expected behavior**

we want to get rid of the wildcard hostnames (Ex: mysqlaaduser@%) for various security reasons in db, so only legit users connect to db from known IP's ( Ex: mysqlaaduser@101.245.% ) when we provision through ASO.

**Additional context**

Do you have a related planned feature coming soon and timelines you have..?
