### ISSUE TITLE
Bug: Code generation for diskAccess fails (v2)

### ISSUE THREAD

**Issue by dseelinger** [Azure/azure-service-operator#1764]
**Describe the bug**
Running `task` to generate code fails after adding the `diskAccess` resource type.

**To Reproduce**
- Add the following to the config azure-arm.yaml file:
```
  - action: include-transitive
    group: microsoft.compute
    version: v*api20200930
    name: diskAccess
    because: "including disk access"
```
- Run `task`

**Expected behavior**
Successful code generation

**Actual behavior**
```
[controller:generate-types] failed during pipeline stage 27/46: Apply flattening to properties marked for flattening: visit of type of "github.com/Azure/azure-service-operator/hack/generated/apis/microsoft.compute/v1alpha1api20200930/DiskAccesses_Spec" failed: flatten applied to non-object type: map[string]k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/JSON
task: Failed to run task "controller:quick-checks": task: Failed to run task
```

**Comment by matthchr** [comment]
Thanks for filing this.

The problem is that the `DiskAccess` "properties" field is actually entirely readonly. This is related to #1474 which is in turn related to https://github.com/Azure/azure-resource-manager-schemas/issues/835.

A fix for this is to include 
```yaml
typeTransformers:
  ...
  # Deal with readonly properties that were not properly pruned in the JSON schema
  ...
  - group: microsoft.compute
    version: v*api20200930
    name: DiskAccesses_Spec
    property: Properties
    remove: true
    because: it has no writable properties in swagger
```
