### ISSUE TITLE
Bug: MySQLUser v1alpha2 does support granting ALL privileges to a database

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1770]
**Describe the bug**
`MySQLUser` resources at `v1alpha2` don't support granting `ALL` privileges. On `v1alpha1` this worked fine.

**To Reproduce**
Create a `MySQLServer` and `MySQLDatabase`, then deploy a user with a grant for all permissions on the database:
```
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLUser
metadata:
  name: myuser
  namespace: myns
spec:
  resourceGroup: myrg
  server: myserver
  username: myuser
  databaseRoles:
    mydb:
    - ALL
```

**Expected behavior**
The user is created and granted all privileges on the specified database.

**Additional context**
The user is created, but not granted any privileges on the database. If you change the privilege to `SELECT`, you can see that it correctly grants the user `SELECT` privilege on the database.
