### ISSUE TITLE
Feature: Supporting mongo DB collection creation in cosmos

### ISSUE THREAD

**Issue by Am2901** [Azure/azure-service-operator#1801]
Hi, Azure developers, 

We try to provision mongo db as cosmos backend db engine by azure service operator.

but looks like operator doesn't support this feature right now. 

Do you have plan to support this feature in operator ?

Thank you.

**Comment by matthchr** [comment]
You can create a Cosmos DB with Mongo DB backend with the following YAML
```yaml
apiVersion: azure.microsoft.com/v1alpha1
kind: CosmosDB
metadata:
  name: cosmosdb-sample-1
spec:
  # #possible values are 'GlobalDocumentDB', 'MongoDB'. 
  kind: MongoDB
  location: westus
  resourceGroup: resourcegroup-azure-operators
  properties:
    databaseAccountOfferType: Standard
    # #Optionally set the capabilities name to the following options: (the default is SQL)
    # #"EnableCassandra", "EnableTable", "EnableGremlin", "EnableMongo"
    # #NOTE: If using "EnableMongo" kind must be set to MongoDB for this to take effect
    capabilities: 
    - name: "EnableMongo"

    # #optionally set the mongoDBVersion to "3.2" or "3.6", if omitted the default is "3.2"
    # #NOTE: kind must be set to MongoDB for this to take effect
    # mongoDBVersion: "3.6"

    # #enable virtual network rules if configured below
    isVirtualNetworkFilterEnabled: true
```

so I think this is supported today?
