### ISSUE TITLE
Bug: aadpodidbinding labels values is not allowed by RFC1123

### ISSUE THREAD

**Issue by yusaito04** [Azure/azure-service-operator#1843]
**Describe the bug**
The value of the azureoperator-controller-manager pod's label `aadpodbinding` is not allowed by RFC1123.
According to [this file](https://github.com/Azure/azure-service-operator/blob/master/charts/azure-service-operator/templates/generated/apps_v1_deployment_azureoperator-controller-manager.yaml), the value of `aadpodbinding` is `aso_manager_binding` and fixed. But the underscore(_) is not allowed by RFC1123, so when I try to create `AzureIdentityBinding`, it always fail.

**To Reproduce**
1. create AKS and enable aadPodIdentity.
2. create Managed Id and assign roles.
3. install aso using helm.
4. run below command to deploy AzureIdentityBinding, and get error.

```
$ az aks pod-identity add --resource-group <rg name> --cluster-name <cluster name> --namespace azureoperator-system --name aso_manager_binding --identity-resource-id <resource id of managed id>
(BadRequest) Name 'aso_manager_binding' is invalid. Please provide a valid and fully qualified DNS name.
$
```

**Expected behavior**
I think the value of label `aadpodidbinding` must be `aso-manager-binding` or without underscore. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44053688/135265330-b5c981f8-7400-40b5-b7b0-37ac6c939753.png)
![image](https://user-images.githubusercontent.com/44053688/135265966-b03059ff-142d-495f-851e-678daf7b72a0.png)

**Additional context**
I used this value.yaml to install helm chart.

```
azureTenantID: <tenant id>
azureSubscriptionID: <subscription id>


azureUseMI: True
azureClientID: <client id of managed id>
aad-pod-identity:
  azureIdentities:
    aso-identity:
      name: aso-identity
      type: 0
      # Update values for Managed Identity
      resourceID: <resource id of managed id>
      clientID: <client id of managed id>
      binding:
        name: aso-identity-binding
        selector: aso-manager-binding
```
