### ISSUE TITLE
Bug: Values sample in the case of using Managed Identity has error

### ISSUE THREAD

**Issue by uya116** [Azure/azure-service-operator#2011]
**Version of Azure Service Operator**
- ASO V1

**Describe the bug**
- [Helm Chart values sample](https://github.com/azure/azure-service-operator/blob/main/docs/v1/howto/helmdeploy.md#managed-identity) in the case of using Managed Identity has error.

now

```
azureUseMI: True
installAadPodIdentity: True
azureClientID: 00000000-0000-0000-0000-000000000000
aad-pod-identity:
    azureIdentity:
        resourceID: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity>"
        clientID: "00000000-0000-0000-0000-000000000000"
```

Expected (reference: https://github.com/Azure/aad-pod-identity/blob/cc8a292b8711b62fcef773dc6b8f978e7401d21a/charts/aad-pod-identity/values.yaml#L266)

```
azureUseMI: True
installAadPodIdentity: True
azureClientID: 00000000-0000-0000-0000-000000000000
aad-pod-identity:
    azureIdentities:
        azureIdentity:
            resourceID: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity>"
            clientID: "00000000-0000-0000-0000-000000000000"
```
