### ISSUE TITLE
Bug: cert-manager v1.6 support

### ISSUE THREAD

**Issue by mkushakov** [Azure/azure-service-operator#2021]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:1.0.22275

**Describe the bug**
When you have cert-manager v1.6 installed on your cluster, it will upgrade existing certificates from [deprecated](https://cert-manager.io/docs/installation/upgrading/upgrading-1.5-1.6/) `v1alpha2` to `v1` apiVersion. But as `v1alpha2` is not supported anymore, you can not upgrade your ASO to latest version as it returns an error:
```
Error: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]
```

**To Reproduce**
1. Install cert-manager via Helm v1.5
2. Install ASO v1 via Helm 1.2.0
3. Upgrade cert-manager to v1.6
4. Try to update ASO v1 to latest 1.8.0 via Helm

**Expected behavior**
ASO should be able to support latest API Version `cert-manager.io/v1`

**Comment by mkushakov** [comment]
Thanks for a fix. If you can't update your existing deployment, you need to update your Helm release by installing https://github.com/helm/helm-mapkubeapis plugin and run it with following Map.yaml file:
```yaml
mappings:
  - deprecatedAPI: "apiVersion: cert-manager.io/v1alpha2\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: cert-manager.io/v1alpha2\nkind: Issuer"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Issuer"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
```
1. Install plugin `helm plugin install https://github.com/helm/helm-mapkubeapis`
2. Create Map.yaml file with content above.
3. Run `helm mapkubeapis RELEASE_NAME -n NAMESPACE --mapfile Map.yaml`
4. Run helm upgrade `helm upgrade --set "certManagerResourcesAPIVersion=cert-manager.io/v1" azure-operator azureserviceoperator/azure-service-operator --version 1.9.0`
