### ISSUE TITLE
Bug: Unable to deploy in v1.22 due ValidatingWebhookConfiguration in admissionregistration.k8s.io/v1beta1 removal

### ISSUE THREAD

**Issue by alfredomagallon** [Azure/azure-service-operator#2047]
**Version of Azure Service Operator**
ASO V1

**Describe the bug**
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"
`
while trying to deploy in k8s v1.22

**To Reproduce**
Deploy k8s v.122 cluster
Try to install the latest V1 helm chart

**Expected behavior**
Should install correctly (all kinds in the correct API groups for recent versions)
Migrate to use the admissionregistration.k8s.io/v1 API versions of ValidatingWebhookConfiguration and MutatingWebhookConfiguration, available since v1.16.

**Comment by nfaust-edb** [comment]
the files is also missing `admissionReviewVersions: ["v1", "v1beta1"]` inside each of the sections.
```
webhooks:
- clientConfig: 
```

**Comment by nfaust-edb** [comment]
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/azureoperator-serving-cert
  name: azureoperator-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: azureoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-azure-microsoft-com-v1alpha1-azuresqlmanageduser
  failurePolicy: Fail
  name: vazuresqlmanageduser.kb.io
  rules:
  - apiGroups:
    - azure.microsoft.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuresqlmanagedusers
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- clientConfig:
    caBundle: Cg==
    service:
      name: azureoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-azure-microsoft-com-v1alpha1-azuresqluser
  failurePolicy: Fail
  name: vazuresqluser.kb.io
  rules:
  - apiGroups:
    - azure.microsoft.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuresqlusers
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
```
