### ISSUE TITLE
Bug: No HTTP resource was found that matches the request URI

### ISSUE THREAD

**Issue by drewz-aware** [Azure/azure-service-operator#2122]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-alpha.5

**Describe the bug**
We receive an error when following the v2 README to create the azure sample resource group.

azure_generic_arm_reconciler.go:518] controllers/ResourceGroupController "msg"="Resource creation failure" "azureName"="" "name"="asosamplerg" "namespace"="default" "error"="{\"message\":\"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/XXXXXX/resourceGroups/?api-version=2020-06-01'.\"}" "resourceID"="/subscriptions/XXXXXX/resourceGroups/"

**To Reproduce**
Create a sample resource group as described in the V2 README

**Expected behavior**
We expect the resource group to be created without error.

**Additional context**
We have verified that the service principle being used by the operator has access to the subscription where the resource group is supposed to be created.

**Comment by matthchr** [comment]
Thanks for this report @drewz-aware. The issue I believe is that the webhooks for ASO are not running. This is causing our defaulting webhook which usually sets the `.spec.AzureName` field to the k8s name to not run, which is causing an attempt to create a resourceGroup with no name (note the `azureName=""` in the log line).

So the question becomes why are the webhooks not running? Can you run these commands?
```
vscode ➜ /go/src (master) $ k get validatingwebhookconfigurations.admissionregistration.k8s.io 
NAME                                                    WEBHOOKS   AGE
azureserviceoperator-validating-webhook-configuration   66         2m57s
cert-manager-webhook                                    1          4m53s
vscode ➜ /go/src (master) $ k get mutatingwebhookconfigurations.admissionregistration.k8s.io 
NAME                                                  WEBHOOKS   AGE
azureserviceoperator-mutating-webhook-configuration   67         3m27s
cert-manager-webhook                                  1          5m23s
vscode ➜ /go/src (master) $ k get pods -n azureserviceoperator-system 
NAME                                                       READY   STATUS    RESTARTS   AGE
azureserviceoperator-controller-manager-5998849ff9-jvmt2   2/2     Running   0          5m19s
vscode ➜ /go/src (master) $ k get services -n azureserviceoperator-system 
NAME                                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
azureserviceoperator-controller-manager-metrics-service   ClusterIP   10.96.22.113    <none>        8443/TCP   5m29s
azureserviceoperator-webhook-service                      ClusterIP   10.96.197.172   <none>        443/TCP    5m29s
```

You should see registered admission and defaulting webhooks and a registered webhook-service. Are those there on your cluster?

**Comment by drewz-aware** [comment]
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                                                                              WEBHOOKS   AGE
azureserviceoperator-validating-webhook-configuration         63         4d1h
cert-manager-webhook                                                                1          11d

kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                                                                            WEBHOOKS   AGE
azureserviceoperator-mutating-webhook-configuration         64         4d1h
cert-manager-webhook                                                               1          11d

kubectl get pods
NAME                                                                                             READY   STATUS    RESTARTS      AGE
azureserviceoperator-controller-manager-d8c689c65-st4hq   2/2     Running   2 (27m ago)   3d2h

kubectl get svc
NAME                                                                                           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
azureserviceoperator-controller-manager-metrics-service   ClusterIP   10.0.107.126   <none>        8443/TCP   4d1h
azureserviceoperator-webhook-service                                   ClusterIP   10.0.224.103   <none>        443/TCP    4d1h

We had noticed the empty string for azureName in that log line but we read that the operator would create the resource using the name of the kubernetes resource when that field was blank. In the V2 README it specifies to use this example...

cat <<EOF | kubectl apply -f -
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: aso-sample-rg
  namespace: default
spec:
  location: westcentralus
EOF

**Comment by drewz-aware** [comment]
I added the azureName to the spec and the resourcegroup was successfully created. Thank for the help!

**Comment by drewz-aware** [comment]
I see that our webhook crd has a different number of webhooks compared to your version, I'll check out ours to see if we have a wrong version.

**Comment by matthchr** [comment]
There should be a mutating webhook for ResourceGroup and my guess is somehow that's not been installed properly. I checked the alpha-5 yaml though and it seems correct to me. This is it just for reference:
```
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: azureserviceoperator-system
      path: /mutate-resources-azure-com-v1alpha1api20200601-resourcegroup
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1alpha1api20200601.resourcegroups.resources.azure.com
  rules:
  - apiGroups:
    - resources.azure.com
    apiVersions:
    - v1alpha1api20200601
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcegroups
  sideEffects: None
```

Can you confirm if that's in your list of webhooks?

**Comment by matthchr** [comment]
When I install the alpha-5 YAML I also have 64 mutating webhooks (my 66 was from alpha-6).

Because I didn't say it well before let me just clarify the expectation here:
> We had noticed the empty string for azureName in that log line but we read that the operator would create the resource using the name of the kubernetes resource when that field was blank. In the V2 README it specifies to use this example...

The defaulting webhook should set AzureName to metadata.name. We always use AzureName in the actual controller so if the webhook doesn't set it, it's not set.

**Comment by drewz-aware** [comment]
We do have the following code in our mutating webhook
```
- admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: XXXX
      service:
        name: azureserviceoperator-webhook-service
        namespace: default
        path: /mutate-resources-azure-com-v1alpha1api20200601-resourcegroup
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: default.v1alpha1api20200601.resourcegroups.resources.azure.com
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - resources.azure.com
        apiVersions:
          - v1alpha1api20200601
        operations:
          - CREATE
          - UPDATE
        resources:
          - resourcegroups
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
```

**Comment by matthchr** [comment]
What version of Kubernetes are you running?

**Comment by drewz-aware** [comment]
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b4d7da0049ead870833a07a1c24ad5ad218fb36c", GitTreeState:"clean", BuildDate:"2022-02-01T10:32:31Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by matthchr** [comment]
Hmm, I see that your webhook service is in the `default` namespace and not `azureoperator-system`

Compare yours vs what is in the alpha-5 yaml:
Yours:
```
- admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: XXXX
      service:
        name: azureserviceoperator-webhook-service
        namespace: default
        path: /mutate-resources-azure-com-v1alpha1api20200601-resourcegroup
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: default.v1alpha1api20200601.resourcegroups.resources.azure.com
```

alpha.5.yaml
```
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: azureserviceoperator-system
      path: /mutate-resources-azure-com-v1alpha1api20200601-resourcegroup
  failurePolicy: Fail
  matchPolicy: Exact
  name: default.v1alpha1api20200601.resourcegroups.resources.azure.com
```

Which namespace is the ASO pod running in?

**Comment by drewz-aware** [comment]
Also the default namespace.

**Comment by matthchr** [comment]
Did you edit the YAML before you installed it to change the namespace that the operator is installed in? My guess is that the issue with webhooks not working stems from being installed into a namespace other than `azureserviceoperator-system`.

The operator should support being installed into another namespace, but there are a bunch of places you'd have to fix things up in the YAML. 

Can you try uninstalling and reinstalling the operator directly from the YAML? (You'll probably need to delete the existing CRDs too before reinstalling, which you can do with `k get crds -o='custom-columns=Name:.metadata.name' | grep azure.com | xargs -I % kubectl delete crd %`). It is advisable to first delete any resources you have created via ASO (so that there aren't any instances of the CRDs in use).

**Comment by drewz-aware** [comment]
I reinstalled into the azureserviceoperator-system namespace but unfortunately ran into the same issue.

**Comment by matthchr** [comment]
Can you share some more details about how exactly you're installing the operator? Is it being installed into an AKS cluster (or `kind`, or something?). Maybe if we have a set of repro steps I can try to reproduce the problem and see what is causing it.

**Comment by drewz-aware** [comment]
Yes we are installing it into an AKS cluster. We're using Flux to install the operator using a helmrelease kind. We've actually installed it previously by having flux install the YAMLs directly, both resulting in the same issue, but currently its using the helm chart here : https://github.com/Azure/azure-service-operator/tree/main/v2/charts/azure-service-operator . We're looking at the main branch for this helm chart, and setting the image to 
```
image:
      repository: mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-alpha.5 
```

**Comment by matthchr** [comment]
Couple of things:
- You should probably avoid the Helm chart for now. If you note, there's not actually a compiled chart there at the moment as we haven't produced one yet. When we do, there will be an `azure-service-operator.v2.0.0-beta.0.tar.gz` there which you can install. We probably shouldn't even show you the other stuff there as it's what we use to _produce_ a chart, not the actual chart itself... See #2128.
- Even once we have a Helm chart, you should avoid specifying an _older_ image than goes with the chart. In this case you're installing a chart from master and pointing `image.repository to mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-alpha.5`. Since `master` is actually at `alpha.6` right now it should point to `alpha.6`.

For now, **I would recommend avoiding the Helm chart and just using**:
`kubectl apply --server-side=true -f https://github.com/Azure/azure-service-operator/releases/download/v2.0.0-alpha.6/azureserviceoperator_v2.0.0-alpha.6.yaml`

I spent some time trying different things, and at least a vanilla 1.22.4 AKS cluster is able to install and run ASO by following the [installation guide](https://azure.github.io/azure-service-operator/#installation). The one difference is to install cert manager 1.7.1 and not 1.1, as 1.1 uses an older version of mutatingwebhookconfiguration that isn't enabled by default in k8s 1.22. Presumably you figured that out as you were able to deploy, but worth confirming.

Here's the exact steps I went through on a vanilla AKS 1.22.4 cluster:

```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml
```

```
k apply -f /home/matthchr/Downloads/azureserviceoperator_v2.0.0-alpha.5.yaml 
namespace/azureserviceoperator-system created
customresourcedefinition.apiextensions.k8s.io/batchaccounts.batch.azure.com created
customresourcedefinition.apiextensions.k8s.io/components.insights.azure.com created
customresourcedefinition.apiextensions.k8s.io/databaseaccounts.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/disks.compute.azure.com created
customresourcedefinition.apiextensions.k8s.io/domains.eventgrid.azure.com created
customresourcedefinition.apiextensions.k8s.io/domainstopics.eventgrid.azure.com created
customresourcedefinition.apiextensions.k8s.io/eventsubscriptions.eventgrid.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleservers.dbformysql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleservers.dbforpostgresql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleserversconfigurations.dbforpostgresql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleserversdatabases.dbformysql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleserversdatabases.dbforpostgresql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleserversfirewallrules.dbformysql.azure.com created
customresourcedefinition.apiextensions.k8s.io/flexibleserversfirewallrules.dbforpostgresql.azure.com created
customresourcedefinition.apiextensions.k8s.io/loadbalancers.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/managedclusters.containerservice.azure.com created
customresourcedefinition.apiextensions.k8s.io/managedclustersagentpools.containerservice.azure.com created
customresourcedefinition.apiextensions.k8s.io/mongodbdatabasecollections.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/mongodbdatabasecollectionthroughputsettings.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/mongodbdatabases.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/mongodbdatabasethroughputsettings.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespaces.eventhub.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespaces.servicebus.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespacesauthorizationrules.eventhub.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespaceseventhubs.eventhub.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespaceseventhubsauthorizationrules.eventhub.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespaceseventhubsconsumergroups.eventhub.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespacesqueues.servicebus.azure.com created
customresourcedefinition.apiextensions.k8s.io/namespacestopics.servicebus.azure.com created
customresourcedefinition.apiextensions.k8s.io/networkinterfaces.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/networksecuritygroups.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/networksecuritygroupssecurityrules.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/publicipaddresses.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/redis.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/redisenterprisedatabases.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/redisenterprises.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/redisfirewallrules.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/redislinkedservers.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/redispatchschedules.cache.azure.com created
customresourcedefinition.apiextensions.k8s.io/resourcegroups.resources.azure.com created
customresourcedefinition.apiextensions.k8s.io/roleassignments.authorization.azure.com created
customresourcedefinition.apiextensions.k8s.io/signalrs.signalrservice.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasecontainers.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasecontainerstoredprocedures.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasecontainerthroughputsettings.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasecontainertriggers.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasecontaineruserdefinedfunctions.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabases.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/sqldatabasethroughputsettings.documentdb.azure.com created
customresourcedefinition.apiextensions.k8s.io/storageaccounts.storage.azure.com created
customresourcedefinition.apiextensions.k8s.io/storageaccountsblobservices.storage.azure.com created
customresourcedefinition.apiextensions.k8s.io/storageaccountsblobservicescontainers.storage.azure.com created
customresourcedefinition.apiextensions.k8s.io/storageaccountsqueueservices.storage.azure.com created
customresourcedefinition.apiextensions.k8s.io/storageaccountsqueueservicesqueues.storage.azure.com created
customresourcedefinition.apiextensions.k8s.io/topics.eventgrid.azure.com created
customresourcedefinition.apiextensions.k8s.io/userassignedidentities.managedidentity.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualmachines.compute.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualmachinescalesets.compute.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualnetworkgateways.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualnetworks.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualnetworkssubnets.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/virtualnetworksvirtualnetworkpeerings.network.azure.com created
customresourcedefinition.apiextensions.k8s.io/webtests.insights.azure.com created
customresourcedefinition.apiextensions.k8s.io/workspaces.operationalinsights.azure.com created
role.rbac.authorization.k8s.io/azureserviceoperator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/azureserviceoperator-manager-role created
clusterrole.rbac.authorization.k8s.io/azureserviceoperator-proxy-role created
rolebinding.rbac.authorization.k8s.io/azureserviceoperator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/azureserviceoperator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/azureserviceoperator-proxy-rolebinding created
service/azureserviceoperator-controller-manager-metrics-service created
service/azureserviceoperator-webhook-service created
deployment.apps/azureserviceoperator-controller-manager created
mutatingwebhookconfiguration.admissionregistration.k8s.io/azureserviceoperator-mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/azureserviceoperator-validating-webhook-configuration created
certificate.cert-manager.io/azureserviceoperator-serving-cert created
issuer.cert-manager.io/azureserviceoperator-selfsigned-issuer created
```

```
cat <<EOF | k apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: azureserviceoperator-system
stringData:
  AZURE_SUBSCRIPTION_ID: "$AZURE_SUBSCRIPTION_ID"
  AZURE_TENANT_ID: "$AZURE_TENANT_ID"
  AZURE_CLIENT_ID: "$AZURE_CLIENT_ID"
  AZURE_CLIENT_SECRET: "$AZURE_CLIENT_SECRET"
EOF
```

After this I was successfully able to create a resourcegroup without needing to manually set `AzureName`.

If this still isn't working for you, you should be able to check that the webhook server is running (you'll get a 400 response but at least it's a response) with:
```
$ kubectl run -i --tty alpine --rm --image=alpine --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # 
/ # apk add --no-cache curl
/ # curl https://azureserviceoperator-webhook-service.azureserviceoperator-system.svc:443/mutate-resources-azure-com-v1alpha1api20200601-resourcegroup -k
{"response":{"uid":"","allowed":false,"status":{"metadata":{},"message":"contentType=, expected application/json","code":400}}}
```
