### ISSUE TITLE
Bug: missing "update secret" right in ClusterRole azureserviceoperator-manager-role

### ISSUE THREAD

**Issue by masterphenix** [Azure/azure-service-operator#2343]
**Version of Azure Service Operator**

mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.0

**Describe the bug**
I am getting the following error when creating a storageAccount resource, with the operatorSpec section configured to retrieve service account secrets:
```
secrets "asopocstorage-secret" is forbidden: User "system:serviceaccount:azureserviceoperator-system:default" cannot update resource "secrets" in API group "" in the namespace "demo"
```
This seems to be due to the "update" verb missing in the "azureserviceoperator-manager-role" ClusterRole.

**To Reproduce**
1. Deploy ASOv2 using Helm Chart
2. Create a storageAccount resource in a separate namespace, with an operatorSpec section:
```
  operatorSpec:
    secrets:
      key1:
        name: asopocstorage-secret
        key: key1
      key2:
        name: asopocstorage-secret
        key: key2
      blobEndpoint:
        name: asopocstorage-secret
        key: blobEndpoint
```
3. Wait a couple minutes, and check events in the namespace

**Expected behavior**

- The serviceAccount used to run the ASO manager should have the rights to update secrets
- The helm chart should also provide a way to specify another serviceAccount than default

**Screenshots**
N/A

**Additional context**
N/A
