### ISSUE TITLE
Bug: Duplicate key annotations under Deployment

### ISSUE THREAD

**Issue by oistein** [Azure/azure-service-operator#2440]
**Version of Azure Service Operator**
Helm Chart v2.0.0-beta.1

**Describe the bug**
Duplicate pod spec annotations generated for the deployment. 

**To Reproduce**

```
helm template --repo https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts azure-service-operator --version v2.0.0-beta.1 |grep "kind: Deployment" -A20
kind: Deployment
metadata:
  labels:
    app: azure-service-operator-v2
    control-plane: controller-manager
  name: azureserviceoperator-controller-manager
  namespace: azureserviceoperator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        {}
      annotations:
        kubectl.kubernetes.io/default-logs-container: manager
      labels:
        aadpodidbinding: aso-manager-binding
        control-plane: controller-manager
```

**Expected behavior**
`deployment.spec.template.metadata.annotations` to appear once

This causes the install to fail when installing the helm release via flux. Due to `Duplicate YAML Keys` [here](https://github.com/fluxcd/flux2/issues/1522).
