### ISSUE TITLE
Feature: refrencing to resource properties created by ASO

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2533]
- It would be great if I can reference other object properties created by ASO
- it would be great to have dependencies. creation of one resource depends on the success of another, i.e. terraform's `depends_on`

```
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: app1
  namespace: default
spec:
  location: westus3
  tags:
    app: "app1"
---
apiVersion: managedidentity.azure.com/v1beta20181130
kind: UserAssignedIdentity
metadata:
  name: app1-mi
  namespace: default
spec:
  azureName: app1-mi
  location: westus3
  owner:
    name: app1
  location: westus3
  tags:
    app: "app1"
    type: "managedIdentity"
---
apiVersion: containerregistry.azure.com/v1beta20210901
kind: Registry
metadata:
  name: registry1
  namespace: default
spec:
  azureName: registry1
  owner:
    name: app1
  location: westus3
  adminUserEnabled: false
  sku: 
    name: Standard
  tags:
    managed_by: "Azure Service Operator v2"
    application: "app1"
---
apiVersion: authorization.azure.com/v1alpha1api20200801preview
kind: RoleAssignment
metadata:
  name: registry-mi-role-assignment
  namespace: default
spec:
  location: westus3
  owner: 
    group: containerregistry.azure.com
    name: registry1
    kind: Registry
  # This is the Principal ID of the AAD identity to which the role will be assigned
  # principalId: 000000-0000-0000-0000-000000000000
  # instead of ^^^, would be great if we can use the following:
  principalId: {refrenceToUserAssignedIdentity.spec.principalId}
  roleDefinitionReference:
    # This ARM ID represents "Contributor" - you can read about other built in roles here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
    # 8e3af657-a8ff-443c-a75c-2fe8c4bcb635 = "Owner"
    # armId: /subscriptions/000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635
    # instead of ^^^, use the following:
    role: "Owner" # and then the operator will resolve the ARM ID as role's ARM ID are predefined
    subscription: "000000-0000-0000-0000-000000000000" # optional, otherwise will use the subscription of the resource group
  depends_on: {refrenceToUserAssignedIdentity}

```

**Comment by matthchr** [comment]
I think this is a duplicate of #2435 and #2317 - see https://azure.github.io/azure-service-operator/design/adr-2022-09-reading-status-properties-of-resources/ for the design we decided on.

I'm working on this right now. Plan is for it to be in the next release. If you find other places you want it let us know because we do need to annotate it to support those specific properties.

The nice thing about the operator pattern is that you don't need to do `depends_on` like you would with an ARM template or Terraform. We just figure it out ourselves based on the CRs you give us, so if you say export 2 properties into a configmap and then consume those in another CR, that second CR won't be provisioned until the first two are able to create their configmap and write their values.

**Comment by buzzaII** [comment]
This is interesting - I have a situation where I would like to create a ServiceBus Subscription and then have that autoforward to a ServiceBus Queue - this requires the queue to be created before the subscription (with forwardTo set to the queue name).

I have a race condition on what gets created first, and in some instance the subscription fails to be provisioned if the Queue has not completed provisioning.

eg:
```
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesQueue
metadata:
  name: samplequeue
  namespace: core-sb
spec:
  owner:
    name: core-sb-02

---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopicsSubscription
metadata:
  name: sampletopicsubscription
  namespace: core-sb
spec:
  forwardTo: samplequeue # queue must be there before this is provisioned.
  owner: 
    name: sampletopic
```
