### ISSUE TITLE
Bug: ConfigMap export fails for multi-versioned resources

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2650]
**Describe the bug**

Currently, our generic reconciler checks for implementation of the interface `genruntime.KubernetesExporter` to see if the resource in question has support for exporting properties to configmaps:

``` go 
	// azure_generic_arm_reconciler_instance.go L#514

	// Also check if the resource itself implements KubernetesExporter
	exporter, ok := r.Obj.(genruntime.KubernetesExporter)
	if ok {
		var additionalResources []client. Object
		additionalResources, err = exporter.ExportKubernetesResources(ctx, r.Obj, r.ARMClient, r.Log)
		if err != nil {
			return errors.Wrap(err, "failed to produce resources for export")
		}

		resources = append(resources, additionalResources...)
	}
```

At the point where this code runs, `r.Obj` contains a _hub_ version of the resource.

For resources such as `managedidentity.UserAssignedIdentity` this works fine. In `azure-arm.yaml` we configure the configmap support:

``` yaml
  managedidentity:
    2018-11-30:
      UserAssignedIdentity:
        $export: true
        $supportedFrom: v2.0.0-alpha.1
      Identity_STATUS:
        ClientId:
          $exportAsConfigMapPropertyName: ClientId
        PrincipalId:
          $exportAsConfigMapPropertyName: PrincipalId
        TenantId:
          $exportAsConfigMapPropertyName: TenantId
```

and the required interface implementation occurs on both the _api_ and _storage_ variants of `UserAssignedIdentity`. (The _storage_ variant being the _hub_ version that will be interrogated by the code above.)

![image](https://user-images.githubusercontent.com/1272094/206585228-2fe9a01d-31a6-43c8-92ea-db7809e1930e.png)

However, we run into problems when we have resources that exist across multiple API versions. This was discovered with `postgresql.FlexibleServer`.

![image](https://user-images.githubusercontent.com/1272094/206586648-addc9731-8758-4ffa-bf9e-8fdf80e37b04.png)

The hub version (`v1beta20210601storage`) doesn't have the method `ExportKubernetesResource()`, and even if it did, it would only export any properties present on that version of `FlexibleServer`.

The implementation of `ExportKubernetesResources` on the preview version has the correct implementation (exporting the expected properties), but is never called.

**Expected behavior**

As our generated configmap support can vary from version to version of a resource, we must call the implementation appropriate to the API version used to create the resource.
