### ISSUE TITLE
Bug: Kustomization replaces servicebus namespace name

### ISSUE THREAD

**Issue by buzzaII** [Azure/azure-service-operator#2732]
ASO V2

This looks like a bug with Kustomize, though causing issues with the ServiceBus Namespace CRD

Kustomize is confusing a ServiceBus namespace with a k8s namespace:

kustomize.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - azure-servicebus.yaml
```

azure-servicebus.yaml:
```
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: core-sb-99
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

running:

``` kubectl kustomize ./```
 
 produces this output:
 
```
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: podinfo
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

Notice the name of the ServiceBus namespace is now podinfo when it was supposed to be core-sb-99
