### ISSUE TITLE
Feature: Add Azure Resource Health

### ISSUE THREAD

**Issue by nojnhuh** [Azure/azure-service-operator#2762]
Azure provides a Resource Health API that reports certain issues with certain types of Azure resources. Having that same data accessible from ASO would be useful downstream in projects like [CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure) that already integrate with Resource Health using the Go SDK directly.

Overview: https://learn.microsoft.com/en-us/azure/service-health/resource-health-overview
API docs: https://learn.microsoft.com/en-us/rest/api/resourcehealth/

I imagine that data could either be used to augment the existing `status` of the existing resource or in a new API type that might look something like:
```yaml
kind: ResourceHealth
spec:
  id: <resource ID>
status:
  availabilityState: Available
  ...
```
