### ISSUE TITLE
Bug: Azure operator does not update the storage in k8s after storage Autogrow in Azure

### ISSUE THREAD

**Issue by Technovation22** [Azure/azure-service-operator#2798]
**Describe the bug**
There is a case when postgreSQL Database is provisioned by the initial storage size (5GB) and the `storageAutogrow` is enabled, the database grew to ~65 GB. What is happening is that, this change is not reflected on the Kubernetes side. When reconciliation happens in Kubernetes it is trying to set the storage again to 5GB which is considered as downgrading the resource and an error happens:

```
postgresql.ServersClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="UnsupportedUpdate" Message="Cannot update StorageMB Downscaling for server" 
```
In this case, Azure rejects this update request since it’s a downsizing attempt which makes sense. The issue is azure operator is not synced up correctly after the database autogrow. 

**Expected behavior**
The expected behaviour would be the azure operator updates the resource on the Kubernetes side after outgrowing. The reconciliation request is not failed and it shows that requests go and come back from Kubernetes and Azure and shows that the reconciliation is successful but this issue causes the database in Kubernetes to go to the failed state.

**Additional context**
```
  sku:
    capacity: 16
    family: Gen5
    name: GP_Gen5_16
    tier: GeneralPurpose
  sslEnforcement: Enabled
  storageProfile:
    backupRetentionDays: 30
    geoRedundantBackup: Disabled
    storageAutogrow: Enabled
    storageMB: 5120
```
Questions: 
1. In such scenarios do we need to set both `storageAutogrow` and `storageMB` in Kubernetes at the same time or maybe we have to remove the default storageMB during the first initialization of the instance? (To prevent the issue if this is a known bug)
2. What is the recommendation when the issue happens? Currently in order to fix such issues we have to manually increase the storageMB To a larger size than Azure which is a workaround and can be not safe in prod environment. Are there any other suggestions?
