### ISSUE TITLE
Feature: expose Component's (appinsights) InstrumentationKey and ConnectionString

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2820]
Feature: expose Component's (appinsights) InstrumentationKey and ConnectionString

Azure Service Operator version: 2
apiVersion: insights.azure.com/v1beta20200202

Please consider adding `operatorSpec` to the `Component`

```
  operatorSpec:
    secrets:
      instrumentationKey:
        name: appinsights-secret
        key: instrumentationKey
      connectionString:
        name: appinsights-secret
        key: connectionString
```
