### ISSUE TITLE
Feature: expose Workspace's (operationalinsights) armId

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2821]
Feature: expose Workspace's (operationalinsights) armId

Azure Service Operator version: 2
apiVersion: operationalinsights.azure.com/v1beta20210601

Please consider adding operatorSpec to the Workspace

```
  operatorSpec:
    configMaps:
      armId:
        name: workspace-properties-cm
        key: armId
```
