### ISSUE TITLE
Feature: Add an option to source workspaceResourceReference to Component (insights)

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2822]
The traditional Application Insights will be phased out by February 2024 and will be replaced by the Workspace-based version. In this new version, the `Component` allows the workspace to be sourced via `workspaceResourceReference.armId`. It would be advantageous to expose armId as a K8s configMap (https://github.com/Azure/azure-service-operator/issues/2821) and to provide the capability to reference it.

**Comment by matthchr** [comment]
You can already do this automatically. You just use the `workspaceResourceReference.Group/Kind/Name`.

Just point it to the OperationalInsights workspace kind + name, for example:

```
workspaceResourceReference:
  group: operationalinsights.azure.com
  kind: Workspace
  name: <your workspace name>
```

We maybe need to document that capability better though...
