### ISSUE TITLE
Feature: Add Azure Cognitive Search

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2843]
Feature: Azure Cognitive Search

Did not find a CRD for Azure Cognitive Search. Please, consider adding it.
[ARM tempalte](https://learn.microsoft.com/en-us/azure/templates/microsoft.search/searchservices?pivots=deployment-language-arm-template)

**Comment by mehighlow** [comment]
@super-harsh , could you please add `operatorSpec.secrets` section impelemnting the search

 ```
operatorSpec:
    secrets:
      adminapikey:
        name: search-secret
        key: AdminApiKey
      queryapikey:
        name: search-secret
        key: QueryApiKey
```
