### ISSUE TITLE
Bug: Storage Account resource does not detect drift in networkAcls if the original is empty

### ISSUE THREAD

**Issue by gareth-baker** [Azure/azure-service-operator#2914]
**Version of Azure Service Operator**
v2.0.0-beta.5

**Describe the bug**
I am trying to create StorageAccount resources that maintain state for the networkAcls on those accounts. If a resource is originally created with `virtualNetworkRules` or `ipRules` configured with at least one entry, drift will be managed properly and any new entries created in the Azure portal will be deleted during reconciliation.

However, if I create a resource without any `virtualNetworkRules` or `ipRules` configured, reconciliation does not seem to be deleting rules created in the portal during reconciliation.

**To Reproduce**

- Create a StorageAccount resource like the following:

```
apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccount
metadata:
  name: iprulesnorules
  namespace: default
spec:
  azureName: iprulesnorules
  kind: StorageV2
  largeFileSharesState: Enabled
  location: canadacentral
  minimumTlsVersion: TLS1_2
  networkAcls:
    bypass: Logging
    defaultAction: Deny
  owner:
    name: gareth-worker
  sku:
    name: Standard_LRS
  supportsHttpsTrafficOnly: true
```
- Add a new IpRule or VirtualNetworkRule through the Azure portal on the Storage Account after it is deployed
- Wait for next reconciliation loop

**Expected behavior**
Additional rules created in the portal should be deleted.

**Additional context**
I'm not sure if this is intentional but wanted to see if there is a particular reason why it is working if there are rules configured on the resource.
