### ISSUE TITLE
Feature: How to orchestrate values from other resources for things such as a FlexibleServersFirewallRule or FederatedIdentity

### ISSUE THREAD

**Issue by buzzaII** [Azure/azure-service-operator#2950]
It would be great to give a end to end example of an orchestration with no manual steps required to deploy a infrastructure where some pieces are not know until 'manifest deployment' time - [this](https://github.com/Azure-Samples/azure-service-operator-samples/blob/master/cosmos-todo-list-mi/cosmos-sql-demo.yaml) is pretty close but still requires the manual input of the issuer OIDC url.

Some examples are if we need to add a firewall rule for an aks cluster to access a postgres sql, or provide the OIDC url for a managed identity ?

```
apiVersion: dbforpostgresql.azure.com/v1api20220120preview
kind: FlexibleServersFirewallRule
metadata:
  name: samplefirewallrule
  namespace: default
spec:
  owner:
    name: samplepostgresql
  startIpAddress: 1.2.3.4 <-- need to add the AKS clusters ip here 
  endIpAddress: 1.2.3.4
```
```
# from sample here: https://github.com/Azure-Samples/azure-service-operator-samples/blob/master/cosmos-todo-list-mi/cosmos-sql-demo.yaml
apiVersion: managedidentity.azure.com/v1beta20220131preview
kind: FederatedIdentityCredential
metadata:
  name: pod-identity
spec:
  audiences:
  # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/


  issuer: ${AKS_OIDC_ISSUER} <-  how would this be supplied ?


  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:cosmos-todo:cosmos-service-account
```

**Comment by theunrepentantgeek** [comment]
Hi @buzzaII, we're working to understand your actual requests.

For securely enabling access to a PostgreSQL server from an AKS cluster, the usual Azure solution would be to create a [VirtualNetwork](https://azure.github.io/azure-service-operator/reference/network/v1api20201101/#network.azure.com/v1api20201101.VirtualNetwork) (aka VNet) with both the database server and your cluster as members.

Given that a VNet provides better isolation and control, why would you need to use IP addresses? 
Or was this just a motivational example?
Either way, this sounds like a good scenario for a more detailed case study showing how things might work.

For [`FederatedIdentity`](https://azure.github.io/azure-service-operator/reference/managedidentity/v1api20220131preview/#managedidentity.azure.com/v1api20220131preview.FederatedIdentityCredential), we can easily make the `issuer` and `subject` configurable, generating some additional support. You can see how this works on the [ServersAdministrator](https://azure.github.io/azure-service-operator/reference/sql/v1api20211101/#sql.azure.com/v1api20211101.ServersAdministrator) object - look for the parallel properties `sid` and `sidFromConfig`. 

Let us know if you'd like us to do this. 

Or, are you looking for a _general_ ability to define any resource property using some kind of expression language? We're aware of the way you can do this with ARM templates - and we're also well aware (through experience) of the configuration burden and maintenance issues that this has often created. We've previously been reluctant to go down that path because it adds an enormous level of complexity with relatively modest benefits. We can reconsider this position if it's a feature that you'd find highly valuable.

(To illustrate the complexity problem, consider the presence of an expression that can't be evaluated. Should this result in omission of that one property when we create the resource, or do we skip the resource until evaluation is possible? In earlier discussions we concluded that we'd likely need to decide this individually for every property, and that there may even be cases where users would want to decide this for themselves.)

Let us know what you're thinking of, and we can work to turn this into some concrete items on our backlog.

**Comment by pb-adrianbezzina** [comment]
Thanks for the response, it was more motivational as I would like to understand how we 'stich' together at operator execution time vs an upstream process collating these pieces of information.

Take the below example - the issuer property is actually the output parameter of the cluster [issuerUrl](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230202preview/#containerservice.azure.com/v1api20230202preview.ManagedClusterOIDCIssuerProfile_STATUS) , even the ability to export any arbitrary resource to a configmap (or secret) and then reference that in any required manifest would be ideal - but currently it looks like only select parameters are exported to configmaps or can be used from configmaps as described [here](https://azure.github.io/azure-service-operator/guide/configmaps/).
```

# from sample here: https://github.com/Azure-Samples/azure-service-operator-samples/blob/master/cosmos-todo-list-mi/cosmos-sql-demo.yaml
apiVersion: managedidentity.azure.com/v1beta20220131preview
kind: FederatedIdentityCredential
metadata:
  name: pod-identity
spec:
  audiences:
  # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/

  issuer: ${AKS_OIDC_ISSUER} <-  how would this be supplied ?

  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:cosmos-todo:cosmos-service-account
```

**Comment by buzzaII** [comment]
Thanks for the reply @theunrepentantgeek, it was more motivational as I would like to understand how we 'stich' together at operator execution time vs an upstream process collating these pieces of information.

Take the below example - the **_issuer_** property is actually the output parameter of the cluster [issuerUrl](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230202preview/#containerservice.azure.com/v1api20230202preview.ManagedClusterOIDCIssuerProfile_STATUS) , even the ability to export any arbitrary resource to a configmap (or secret) and then reference that in any required manifest would be ideal - but currently it looks like only select parameters are exported to configmaps or can be used from configmaps as described [here](https://azure.github.io/azure-service-operator/guide/configmaps/).
```

# from sample here: https://github.com/Azure-Samples/azure-service-operator-samples/blob/master/cosmos-todo-list-mi/cosmos-sql-demo.yaml
apiVersion: managedidentity.azure.com/v1beta20220131preview
kind: FederatedIdentityCredential
metadata:
  name: pod-identity
spec:
  audiences:
  # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/

  issuer: ${AKS_OIDC_ISSUER} <-  how would this be supplied ?

  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:cosmos-todo:cosmos-service-account
```
