### ISSUE TITLE
Bug: Resource with reconcile-policy: skip doesn't populate ConfigMap

### ISSUE THREAD

**Issue by skinny** [Azure/azure-service-operator#2985]
**Describe the bug**
Using ASO V2 I expect an `UserAssignedIdentity` to populate the `ConfigMap` described in the `operaterSpec`. This works, but when I introduce the `serviceoperator.azure.com/reconcile-policy: skip` (because this is an already existing identity) the `ConfigMap` is not created/populated

**To Reproduce**
- Deploy an `UserAssignedIdentity` with the following yaml :  

```
apiVersion: managedidentity.azure.com/v1beta20181130
kind: UserAssignedIdentity
metadata:
  name: umi-my-app
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
spec:
  location: westeurope
  owner:
    name: rg-umi-my-app
  operatorSpec:
    configMaps:
      principalId:
        name: deploy-identity
        key: principalId
      clientId:
        name: deploy-identity
        key: clientId
      tenantId:
        name: deploy-identity
        key: tenantId

```
**Expected behavior**
The `deploy-identity` configmap should be created and populated just like when the UAI is created as a an ASO managed resource.

**Screenshots**
n/a

**Additional context**
n/a
