### ISSUE TITLE
Bug: Helm chart not deploy all CRDs available

### ISSUE THREAD

**Issue by javierdompablo** [Azure/azure-service-operator#2989]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1

**Describe the bug**
I am trying to deploy the DnsZonesCNAMERecord object that is found from version v1api20180501 but the operator does not install that version of crds

**To Reproduce**

❯ kubectl api-versions | grep network.azure.com
network.azure.com/v1api20180901
network.azure.com/v1api20180901storage
network.azure.com/v1api20200601
network.azure.com/v1api20200601storage
network.azure.com/v1api20201101
network.azure.com/v1api20201101storage
network.azure.com/v1api20220701
network.azure.com/v1api20220701storage
network.azure.com/v1beta20180901
network.azure.com/v1beta20180901storage
network.azure.com/v1beta20201101
network.azure.com/v1beta20201101storage

I am applying the repository example to create this object

``` yaml
apiVersion: network.azure.com/v1api20180501
kind: DnsZonesCNAMERecord
metadata:
  name: aso-sample-record-cname
  namespace: default
spec:
  CNAMERecord:
    cname: asosample.com
  owner:
    name: aso-sample-dz.com
  TTL: 3600
```

and the error says you don't have this resource

``` bash
error: resource mapping not found for name: "aso-sample-record-cname" namespace: "default" from "DNSrecordError.yaml": no matches for kind "DnsZonesCNAMERecord" in version "network.azure.com/v1api20180501"
ensure CRDs are installed first
```

**Expected behavior**
The operator install al the API version available
