### ISSUE TITLE
Bug: References to virtual network in Azure Keyvault error

### ISSUE THREAD

**Issue by javierdompablo** [Azure/azure-service-operator#3008]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0

**Describe the bug**
I am trying to reference an armID from a key vault to add a virtual network but I get the following error.

```
"test.yaml": admission webhook "default.v1api20210401preview.vaults.keyvault.azure.com" denied the request: json: cannot unmarshal string into Go struct field VirtualNetworkRule.spec.properties.networkAcls.virtualNetworkRules.reference of type genruntime.ResourceReference
```

**To Reproduce**
```
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: test
spec:
  location: westeurope
  owner:
    name: test-rg-dev-westeurope-000
  properties:
    tenantId: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    sku:
      family: A
      name: standard
    enableSoftDelete: true
    enablePurgeProtection: true
    enableRbacAuthorization: false
    networkAcls: 
        bypass: "AzureServices"
        defaultAction: "Deny"
        virtualNetworkRules: 
        - reference: /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test-rg-dev-westeurope-000/providers/Microsoft.Network/virtualNetworks/test/subnets/public
```

**Expected behavior**
The resource recognize the subnet ID and apply in Virtual Networks into Key Vault

**Comment by matthchr** [comment]
It should be:
```
    networkAcls: 
        bypass: "AzureServices"
        defaultAction: "Deny"
        virtualNetworkRules: 
        - reference:
            armId: /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test-rg-dev-westeurope-000/providers/Microsoft.Network/virtualNetworks/test/subnets/publi
```

You can see that described [here](https://azure.github.io/azure-service-operator/reference/keyvault/v1api20210401preview/#keyvault.azure.com/v1api20210401preview.NetworkRuleSet), where if you click through you see the `reference` field is: https://pkg.go.dev/github.com/Azure/azure-service-operator/v2/pkg/genruntime#ResourceReference
