### ISSUE TITLE
Improve validation to catch use of armID as name

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3019]
**Describe the current behavior**

A user inadvertently set up a resource reference this way:

``` yaml
  workspaceResourceReference:
    group: operationalinsights.azure.com
    kind: Workspace
    name: /subscriptions/<rest of the ARM ID>
```

This didn't work, as the expected structure for references using ARM IDs is this:

``` yaml
  workspaceResourceReference:
    armId: /subscriptions/<rest of the ARM ID>
```

**Describe the improvement**

The error message was accurate, but not as informative as it could be.

I'm wondering if we could improve the error handling to detect the case where something goes wrong and `name` has been populated with something that looks more like an `armID` than it does like a `name`. 

Perhaps something like some of the errors from **git** where it gives a suggestion. For example, what if the error included `name looks like it might be an ARM ID; did you mean armID: /subscriptions/<rest of the ARM ID> ?`
