### ISSUE TITLE
Improvement: Azure Cognitive Search: Auth mode and Keys

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#3053]
**Describe the current behavior**
Azure Cognitive Search is available with ASO version 2.1.0; however, it is not possible to set the desired API access control. The service gets created with 'API keys' access control by default.

**Describe the improvement**
It would be great to have an option for defining API access control and obtaining the AdminApiKey and QueryApiKey as secrets with `operatorSpec`, for example:

```
operatorSpec:
   secrets:
     adminapikey:
       name: search-secret
       key: AdminApiKey
     queryapikey:
       name: search-secret
       key: QueryApiKey
```

A minor improvement could be adjusting the SKU to the standard (if possible) that other Azure services have - where the SKU starts with a capital letter.
```
│   │   ├── Sku: *Object (1 property)
│   │   │   └── Name: *Enum (7 values)
│   │   │       ├── "basic"
│   │   │       ├── "free"
│   │   │       ├── "standard"
│   │   │       ├── "standard2"
│   │   │       ├── "standard3"
│   │   │       ├── "storage_optimized_l1"
│   │   │       └── "storage_optimized_l2"
```

**Additional context**
https://github.com/Azure/azure-service-operator/issues/2843#issuecomment-1518375581
