### ISSUE TITLE
virtualNetworks-vnet not supported for storageaccount and SQL

### ISSUE THREAD

**Issue by amitganvir23** [Azure/azure-service-operator#3123]
I have deployed azure oeprator 2.1.0 and able to create ResourceGroup and when i am trying to create StorageAccount it is giving 403 access denied and looks like it is using public endpoint but I would like to use our vnat but i didnt find any option for stoargeaccount yaml file..

kubectl get StorageAccount
evmagentamlflowstorage   False   Error      RequestDisallowedByPolicy   Resource 'devmagentamlflowstorage' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"PA-Storage","id":"/providers/Microsoft.Management/managementGroups/CloudIntegrated/providers/Microsoft.Authorization/policyAssignments/fsdfsdfdfdfdsfdsfsf"},"policyDefinition":

In terraform I am able to do that using  object "virtual_network_subnet_ids" and we already have virtualNetworks/vnet ID but unable to use this for creating Storage account

**Comment by matthchr** [comment]
I don't see any reference to `virtual_network_subnet_ids` [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_account). Could you clarify which specific property from Terraform you want?

I _think_ you want to configure your storage to use your VNET and private access to comply with your Azure Policy. You can do that with ASO v2.1.0.

Check our [API documentation](https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/), there are a few fields:
`publicNetworkAccess` and `networkAcls` are the two interesting ones:

For `publicNetworkAccess` you can set it to `Disabled` to disable public network access. It's not clear to me if you want this _and_ `networkAcls` or just `networkAcls`.

`networkAcls` is a complex type that looks [like this](https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/#storage.azure.com/v1api20220901.NetworkRuleSet):
```
  networkAcls:
    virtualNetworkRules:
      - action: Allow
        reference:
          armID: <your ARM ID here>
```

Pay special attention to the `networkAcls.defaultAction` property as well, as you may want to set that to `Deny` (I'm not 100% sure what your policy requires).

**Comment by amitganvir23** [comment]
@matthchr still it didnt work for v2 helm charts

Let me explain what steps i have followed
**Step1:** `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.2/cert-manager.yaml`

**Step2:** extract helm charts https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator-v2.1.0.tgz

**Step3:** Deploy helm charts
` cd azure-service-operator
helm upgrade --install azure-service-operator . \
     --create-namespace \
     --namespace=azureserviceoperator-system \
     --set azureSubscriptionID=aaaaaaaaaaaaaaaaaaa \
     --set azureTenantID=aaaaaaaaaaaaaaaaaaa \
     --set azureClientID=aaaaaaaaaaaaaaaaaaa \
     --set azureClientSecret=aaaaaaaaaaaaaaaaaaa \
     --set crdPattern='resources.azure.com/*;storage.azure.com/*;authorization.azure.com/*'
`
**Step4:** Created resources.yaml file and Able to create resources on Azure platform
```
apiVersion:  resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: dev-magenta-mlflow-rg # it will create Resource Group in Azure platform
  namespace: default
spec:
  location: Westeurope
```
**Here I am getting error for creating Storage account**
**Step5:** Trying create storage account and its using public endpoint and giving error. 
```
apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: devmagentamlflowstorage
  namespace: az-mlflow
spec:
  location: Westeurope
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: dev-mlflow-rg
  accessTier: Hot
```

It is not supporting virtual_network_subnet_ids for example below is my vnet subnetid. I also tried networkAcls but it is giving same error.
`- subnetId: /subscriptions/aaaaaaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_dev12/subnets/DevSubnet"`

`apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: devmagentamlflowstorage
  namespace: default
spec:
  location: Westeurope
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: dev-mlflow-rg
  accessTier: Hot
  networkAcls:
    defaultAction: Deny
    virtualNetworkRules:
      - action: Allow
        reference:
          armId: "/subscriptions/aaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_dtit_dev_123/subnets/DevSubnet"
`

**Comment by theunrepentantgeek** [comment]
@amitganvir23, would you please clarify the issue you're having? We'd like to help get you past this blocker.

@matthchr asked
> Could you clarify which specific property from Terraform you want?
Knowing which exact Terraform feature you're referencing would help us understand the nature of your problem.

Further, your examples show you trying to create a StorageAccount that would use your VNET, but the single error message you've shared indicates a HTTP 403 error to do with a policy that seems to be unrelated. How do these relate? What's the policy that's blocking the creation of the StorageAccount?

Lastly, the issue title references SQL, but you make no mention of it in the body of the issue. Which SQL resources are you trying to use (MySQL, PostgreSQL or SQL Server?), and what's the exact error you're encountering?

**Comment by amitganvir23** [comment]
Hi @theunrepentantgeek ,

I followed above steps but i am getting below error while creating storage account and we dont have direct access of azure resources hence we are using private subnet. I also tried to with Deny and Allow for storageaccount but still facing same error

`I0711 08:26:21.069362       1 common.go:57] controllers/StorageAccountController "msg"="Reconcile invoked" "annotations"={"serviceoperator.azure.com/operator-namespace":"azureserviceoperator-system"} "conditions"="[Condition [Ready], Status = \"False\", ObservedGeneration = 2, Severity = \"Warning\", Reason = \"WaitingForOwner\", Message = \"Owner \\\"dev-magenta-mlflow-rg2, Group/Kind: resources.azure.com/ResourceGroup\\\" cannot be found. Progress is blocked until the owner is created.\", LastTransitionTime = \"2023-07-11 08:26:09 +0000 UTC\"]" "creationTimestamp"="2023-07-11T08:17:47Z" "finalizers"=null "generation"=2 "kind"={"kind":"StorageAccount","apiVersion":"storage.azure.com/v1api20220901storage"} "name"="devmagentamlflowstorage" "namespace"="default" "owner"={"group":"resources.azure.com","kind":"ResourceGroup","name":"dev-magenta-mlflow-rg2"} "ownerReferences"=null "resourceVersion"="7427856" "uid"="96ebc9f6-31d7-4eeb-8c5d-95e18d04378d"
I0711 08:26:21.069399       1 common.go:124] controllers/StorageAccountController "msg"="applying ownership" "name"="devmagentamlflowstorage" "namespace"="default"
I0711 08:26:21.069448       1 common.go:72] controllers/StorageAccountController "msg"="Owner does not yet exist" "NamespacedName"={"Namespace":"default","Name":"dev-magenta-mlflow-rg2"} "name"="devmagentamlflowstorage" "namespace"="default"
E0711 08:26:21.069481       1 generic_reconciler.go:175] controllers/StorageAccountController "msg"="Error claiming resource" "error"="Reason: WaitingForOwner, Severity: Warning, RetryClassification: RetryFast, Cause: Owner \"dev-magenta-mlflow-rg2, Group/Kind: resources.azure.com/ResourceGroup\" cannot be found. Progress is blocked until the owner is created." "name"="devmagentamlflowstorage" "namespace"="default"
E0711 08:26:21.069516       1 generic_reconciler.go:346] controllers/StorageAccountController "msg"="Encountered error impacting Ready condition" "error"="Reason: WaitingForOwner, Severity: Warning, RetryClassification: RetryFast, Cause: Owner \"dev-magenta-mlflow-rg2, Group/Kind: resources.azure.com/ResourceGroup\" cannot be found. Progress is blocked until the owner is created." "name"="devmagentamlflowstorage" "namespace"="default"
I0711 08:26:21.141485       1 generic_reconciler.go:92] controllers/StorageAccountController "msg"="Encountered error, re-queuing..." "name"="devmagentamlflowstorage" "namespace"="default" "result"={"Requeue":false,"RequeueAfter":30000000000}`

I also tried to use pod-identity that is also facing some error while configuring for azure,
below is the link i was trying to follow
https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity


I am getting error below for pod-identity while creating resourcesgroup from yaml file.

`0710 07:57:30.986737       1 common.go:57] controllers/ResourceGroupController "msg"="Reconcile invoked" "annotations"={"serviceoperator.azure.com/operator-namespace":"azureserviceoperator-system","serviceoperator.azure.com/resource-id":"/subscriptions/2e9b88fa-5438-41b9-b039-9e4aa06756c3/resourceGroups/dev-magenta-mlflow-rg2"} "conditions"="[Condition [Ready], Status = \"False\", ObservedGeneration = 1, Severity = \"Warning\", Reason = \"UnknownError\", Message = \"DefaultAzureCredential authentication failed\\nGET http://169.254.169.254/metadata/identity/oauth2/token\\n--------------------------------------------------------------------------------\\nRESPONSE 400 Bad Request\\n--------------------------------------------------------------------------------\\n{\\n  \\\"error\\\": \\\"invalid_request\\\",\\n  \\\"error_description\\\": \\\"Identity not found\\\"\\n}\\n--------------------------------------------------------------------------------\\n\", LastTransitionTime = \"2023-07-10 07:57:27 +0000 UTC\"]" "creationTimestamp"="2023-07-10T07:57:26Z" "finalizers"=["serviceoperator.azure.com/finalizer"] "generation"=1 "kind"={"kind":"ResourceGroup","apiVersion":"resources.azure.com/v1api20200601storage"} "name"="dev-magenta-mlflow-rg2" "namespace"="default" "owner"=null "ownerReferences"=null "resourceVersion"="6223644" "uid"="a31e4363-b397-4cf8-98e6-1c2e29f53dd6"`

**Comment by amitganvir23** [comment]
We have private aks cluster and below is the command used to create our aks and we used --vnet-subnet-id in terraform.

```
az aks create \
  --resource-group testing \
  --name test-cluster-new \
  --load-balancer-sku standard \
  --enable-private-cluster \
  --network-plugin kubenet \
  --network-policy calico \
  --vnet-subnet-id "/subscriptions/aaaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_abc/subnets/dev" \
  --service-principal "aaaaaaaaaaaaaaaa" \
  --client-secret "aaaaaaaaaaaaaaaa" \
  --docker-bridge-address 172.17.0.1/16 \
  --dns-service-ip 10.2.0.10 \
  --service-cidr 10.2.0.0/24 \
  --pod-cidr 10.244.0.0/16
```

**Comment by theunrepentantgeek** [comment]
I'm not an expert in Azure Policy, but it looks to me as though you can't create your `StorageAccount` because it doesn't comply with your organizations own policies.

The first `PolicyViolation` included in the error message you posted has the name `PD-DenyPublicAccessToStorageAccount` and this expression block:

``` json
{
    "result": "False",
    "expressionKind": "Field",
    "expression": "Microsoft.Storage/storageAccounts/allowBlobPublicAccess",
    "path": "properties.allowBlobPublicAccess",
    "targetValue": "false",
    "operator": "Equals"
}
```
This seems to be indicating you haven't set `allowBlobPublicAccess` to false.

The field `allowBlobPublicAccess` is [supported by ASO](https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/#storage.azure.com/v1api20220901.StorageAccount), but you haven't included it in your resource definition. The documentation for `allowBlobPublicAccess` reads

> Allow or disallow public access to all blobs or containers in the storage account. The default interpretation is true for this property.

Since the policy requires the value to be `false`, you'll need to add `allowBlobPublicAccess: false` to your resource YAML.

The second `PolicyViolation` listed in your error message has the name `PD-EnforceInfrastructureEncryptionForStorageAccounts`, and this expression block:

``` json
{
    "result": "True",
    "expressionKind": "Field",
    "expression": "Microsoft.Storage/storageAccounts/encryption.requireInfrastructureEncryption",
    "path": "properties.encryption.requireInfrastructureEncryption",
    "targetValue": "true",
    "operator": "NotEquals"
},
```

This is indicating that you haven't set `encryption.requireInfrastructureEncryption` to true. 

Again, this is property is [supported by ASO](https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/#storage.azure.com/v1api20220901.Encryption).

I believe that if you modify your `StorageAccount` to comply with your own organizations policy requirements, creation will work.

**Comment by theunrepentantgeek** [comment]
I've searched extensively for documentation of the `--vnet-subnet-id` flag for Terraform, but haven't found it.

As an educated guess, maybe it's a flag telling Terraform to use that VNet when communicating with ARM? If so, that flag is needed because the Terraform CLI runs outside your cluster, and it needs to know about the VNet explicitly.

ASO doesn't need to do that. Based on your use of `--vnet-subnet-id` with `az aks create`, your AKS cluster is a member of the VNet. As ASO is running within that cluster, the ARM URL used by ASO naturally resolves (via DNS) to the correct private endpoint within your VNet. No explicit configuration of ASO is required for this.

**Comment by amitganvir23** [comment]
@matthchr still it didnt work for v2 helm charts

Let me explain what steps i have followed
**Step1:** `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.2/cert-manager.yaml`

**Step2:** extract helm charts https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator-v2.1.0.tgz

**Step3:** Deploy helm charts
```
cd azure-service-operator
helm upgrade --install azure-service-operator . \
     --create-namespace \
     --namespace=azureserviceoperator-system \
     --set azureSubscriptionID=aaaaaaaaaaaaaaaaaaa \
     --set azureTenantID=aaaaaaaaaaaaaaaaaaa \
     --set azureClientID=aaaaaaaaaaaaaaaaaaa \
     --set azureClientSecret=aaaaaaaaaaaaaaaaaaa \
     --set crdPattern='resources.azure.com/*;storage.azure.com/*;authorization.azure.com/*'

```
**Step4:** Created resources.yaml file and Able to create resources on Azure platform
```
apiVersion:  resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: dev-magenta-mlflow-rg # it will create Resource Group in Azure platform
  namespace: default
spec:
  location: Westeurope
```
**Here I am getting error for creating Storage account**
**Step5:** Trying create storage account and its using public endpoint and giving error. 
```
apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: devmagentamlflowstorage
  namespace: az-mlflow
spec:
  location: Westeurope
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: dev-mlflow-rg
  accessTier: Hot
```

It is not supporting virtual_network_subnet_ids for example below is my vnet subnetid. I also tried networkAcls but it is giving same error.
`- subnetId: /subscriptions/aaaaaaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_dev12/subnets/DevSubnet"`

```
apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: devmagentamlflowstorage
  namespace: default
spec:
  location: Westeurope
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: dev-mlflow-rg
  accessTier: Hot
  networkAcls:
    defaultAction: Allow
    virtualNetworkRules:
      - action: Allow
        reference:
          armId: "/subscriptions/aaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_dtit_dev_123/subnets/DevSubnet"

```

**Comment by amitganvir23** [comment]
Hello,
Now i am trying to use Pod user Manage Identity instead of service principle, Now I am able to update pod identity on my cluster and but now while trying to create ResoureGroup I am getting following error

```
      message: "DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential:
        incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID
        are set\n\tWorkloadIdentityCredential: no token file specified. Check pod
        configuration or set TokenFilePath in the options\n\tManagedIdentityCredential:
        managed identity timed out\n\tAzureCLICredential: fork/exec /bin/sh: no such
        file or directory"
      observedGeneration: 1
      reason: UnknownError 
```

Below are the steps I have performed it on our Private AKS cluster

Step1:
```
az aks update \
    --resource-group dev \
    --name dev-cluster  \
    --enable-managed-identity \
    --assign-identity /subscriptions/aaaaaaaaaa/resourceGroups/dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dev-azureoperator
```
```
az aks update --enable-pod-identity --name dev-magenta-mlops-cluster --resource-group dev-magenta --enable-pod-identity-with-kubenet
```
export POD_IDENTITY_NAMESPACE=azureserviceoperator-system
export IDENTITY_RESOURCE_ID="/subscriptions/aaaaaaaaaa/resourceGroups/dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dev-azureoperator"
export POD_IDENTITY_NAME=az-pod-identity
az aks pod-identity add --resource-group dev --cluster-name dev-cluster --namespace ${POD_IDENTITY_NAMESPACE}  --name ${POD_IDENTITY_NAME} --identity-resource-id ${IDENTITY_RESOURCE_ID}
```
Step2: I have deployed Azure Operator using v2 helm charts
```
helm upgrade --install azure-service-operator . \
     --create-namespace \
     --namespace=azureserviceoperator-system \
     --set azureSubscriptionID=aaaaaaa \
     --set azureTenantID=aaaaaa \
     --set azureClientID=<Manager Identiy Clientid> \
     --set crdPattern='resources.azure.com/*;storage.azure.com/*;authorization.azure.com/*;managedidentity.azure.com/*'
```

Step3: Here I was getting above error 
Now I am trying to create Resources on Azure
```
apiVersion:  resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: dev-mlflow-rg
  namespace: azureserviceoperator-system
spec:
  location: Westeurope

kubectl create resource.yaml
```

**Comment by amitganvir23** [comment]
Hello @matthchr ,

I have already added pod identity label name in the deployment instead using workload identity.
```
export POD_IDENTITY_NAME=az-pod-identity
export POD_IDENTITY_NAMESPACE=azureserviceoperator-system
export IDENTITY_RESOURCE_ID="/subscriptions/aaaaaaa/resourceGroups/dev-magenta/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dev-azureoperator"
az aks pod-identity add --resource-group dev-magenta --cluster-name test-magenta3 --namespace ${POD_IDENTITY_NAMESPACE}  --name ${POD_IDENTITY_NAME} --identity-resource-id ${IDENTITY_RESOURCE_ID}
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azure-service-operator-v2
    control-plane: controller-manager
  name: azureserviceoperator-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations }}
        {{- end }}
        kubectl.kubernetes.io/default-container: manager
      labels:
        **aadpodidbinding: aaz-pod-identity**
```

We are trying to create resources and storage account from Azure Operator using pod identity instead of Work-load-identity or service principal Client-Secrets. But still I am getting error to create ResoureGroup with the following error.

```
      message: "DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential:
        incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID
        are set\n\tWorkloadIdentityCredential: no token file specified. Check pod
        configuration or set TokenFilePath in the options\n\tManagedIdentityCredential:
        managed identity timed out\n\tAzureCLICredential: fork/exec /bin/sh: no such
        file or directory"
      observedGeneration: 1
      reason: UnknownError 
```

I have few concerns.
1. What is right approach to use Pod Identity for Azure operator
2. How to use Pod Identity for creating Resources and Storage account for azure
3. Any other approach that we can use to achieve this tasks on AKS

**Comment by matthchr** [comment]
> What is right approach to use Pod Identity for Azure operator

Why do you want to use AAD Pod Identity instead of Workload Identity? Workload identity is replacing pod identity. See [the public documentation](https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity), which says:

> The open source Azure AD pod-managed identity (preview) in Azure Kubernetes Service has been deprecated as of 10/24/2022, and the project will be archived in Sept. 2023. For more information, see the [deprecation notice](https://github.com/Azure/aad-pod-identity#-announcement). The AKS Managed add-on begins deprecation in Sept. 2023.

Instead, I recommend you follow [the instructions](https://azure.github.io/azure-service-operator/guide/authentication/credential-format/#azure-workload-identity) for setting up workload identity with ASO. You'll need to enable [OIDC Issuer](https://learn.microsoft.com/en-us/azure/aks/use-oidc-issuer) on your AKS cluster to do this.

If you really _must_ use pod identity, we have instructions for how to set it up here: https://azure.github.io/azure-service-operator/guide/authentication/credential-format/#deprecated-managed-identity-aad-pod-identity.

One thing I note is that in your sample you say works, you have:
> **aadpodidbinding: az-pod-identity**

but for ASO you have

> **aadpodidbinding: aaz-pod-identity**

Is that intentional?

In any case: The strong recommendation from the AKS team is to use workload identity rather than pod identity.

**Comment by amitganvir23** [comment]
I had already tried with workload identity with OIDC issuer but it was giving following error while creating ResourceGroup..
Manage Identity also having contributor access.

Role: Contributor
Description: Grants full access to manage all resources, but does not allow you to assign roles in Azure RBAC, manage assignments in Azure Blueprints, or share image galleries.
Scope: Subscription (Inherited)
Group assignment: AP_GRP_dtit_xya123_contributor
Condition: None




**Resourcegroup yaml file**
```
apiVersion:  resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: dev-magenta-mlflow-rg-amit1
  namespace: azureserviceoperator-system 
spec:
  location: Westeurope
```

**output Error**
```
root@magenta-gitlab-runner-new:~/amit/azure-service-operator/mlflow# kubectl -n azureserviceoperator-system get ResourceGroup
NAME                          READY   SEVERITY   REASON                MESSAGE
dev-magenta-mlflow-rg-amit1   False   Warning    AuthorizationFailed   The client 'bbbbbbbbb' with object id 'bbbbbbbbb' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/write' over scope '/subscriptions/aaaaaaaa/resourceGroups/dev-magenta-mlflow-rg-amit1' or the scope is invalid. If access was recently granted, please refresh your credentials.: PUT https://management.azure.com/subscriptions/aaaaaaaaaaaaa/resourceGroups/dev-magenta-mlflow-rg-amit1...
root@magenta-gitlab-runner-new:~/amit/azure-service-operator/mlflow# 
```
