### ISSUE TITLE
Bug: Can't modify the app.kubernetes.io/managed-by label on CRs

### ISSUE THREAD

**Issue by b1zzu** [Azure/azure-service-operator#3148]
**Version of Azure Service Operator**

`mcr.microsoft.com/k8s/azureserviceoperator:v2.1.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1`

**Describe the bug**

I'm trying to modify the `app.kubernetes.io/managed-by` label of a `storage.azure.com/v1api20220901.StorageAccountsBlobService` resource I've previously created but it fails with the following error:

```
Error from server: failed to prune fields: failed add back owned items: failed to convert pruned object at version storage.azure.com/v1api20220901: conversion webhook for storage.azure.com/v1api20220901storage, Kind=StorageAccountsBlobService returned invalid metadata: invalid metadata of type <nil> in input object
```

**To Reproduce**

`kubectl apply ...` of:

```
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: me
spec:
  owner:
    name: storage-account
```

than `kubectl apply ...` again changing the `app.kubernetes.io/managed-by` label

```
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: someone-else
spec:
  owner:
    name: storage-account
```

**Expected behavior**

I should be able to change the `app.kubernetes.io/managed-by` whenever I want because it identifies the tool/framework/controller I use to create and manage the CR definition.

**Comment by matthchr** [comment]
Sorry for the slow response here - I am looking into this and will get back to you shortly.

**Comment by b1zzu** [comment]
Hi @matthchr do you have any updates for me? I've been testing it with version 2.2.0 and I have the same error.

My workaround is to add `storage` to each resource like this:
```
apiVersion: storage.azure.com/v1api20220901storage
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: someone-else
spec:
  owner:
    name: storage-account
```
