### ISSUE TITLE
Need to Create Storageaccount with existing ResourceGroup

### ISSUE THREAD

**Issue by amitganvir23** [Azure/azure-service-operator#3172]
As per the previous issue, we decided to install Azure operator using Workload Identity on Private AKS Cluster.

Due to limited access on Client environment we cant create ResourecGroup using operator with Managed Identity.
While creating StorageAccount from operator its failing as owner Resourecgroup is not succeed on Kubernetes.

We need to find a way to create Storageaccount with existing ResourecGroup which is already created by terrafrom.

Old Ref ticket: https://github.com/Azure/azure-service-operator/issues/3123

**Comment by matthchr** [comment]
I believe this is a duplicate of #2357. You can see https://github.com/Azure/azure-service-operator/issues/2357#issuecomment-1535234659 for the workaround.

**Comment by amitganvir23** [comment]
Do we have any solution for this issue.

**Comment by amitganvir23** [comment]
Thanks, issue is resolved now, I am able to create resources and Storageaccount with the following yaml file.

```
apiVersion:  resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: kubeflowtesting
  namespace: default
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
spec:
  location: Westeurope
```

```
apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: amit4
  namespace: default
spec:
  location: Westeurope
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: kubeflowtesting
  accessTier: Hot
  allowBlobPublicAccess: false
  allowCrossTenantReplication: false
  allowSharedKeyAccess: false
  encryption:
    keySource: Microsoft.Storage
    requireInfrastructureEncryption: true
    services:
      blob:
        enabled: true
  networkAcls:
    defaultAction: Deny
    virtualNetworkRules:
      - action: Allow
        reference:
          armId: "/subscriptions/aaaaaaa/resourceGroups/rg-ci-vnet/providers/Microsoft.Network/virtualNetworks/vnet_abc/subnets/TestSubnet"
```
