### ISSUE TITLE
The api-version '2021-05-01' is invalid for flexibleservers

### ISSUE THREAD

**Issue by amitganvir23** [Azure/azure-service-operator#3197]
I have install operator from https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator-v2.1.0.tgz

I am trying to create resources for flexibleserver which is exsist but its failing for api version

I am getting following Error

```
       --------------------------------------------------------------------------------
        RESPONSE 400: 400 Bad Request
        ERROR CODE: InvalidApiVersionParameter
        --------------------------------------------------------------------------------
        {
          "error": {
            "code": "InvalidApiVersionParameter",
            "message": "The api-version '2021-05-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
          }
        }
        --------------------------------------------------------------------------------
```

I have tried with both api version

```
apiVersion: dbformysql.azure.com/v1beta20210501
apiVersion: dbformysql.azure.com/v1api20210501

```

Below is my yaml file
```
apiVersion: dbformysql.azure.com/v1beta20210501
kind: FlexibleServer
metadata:
  name: dev-mlops-mlflow
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
spec:
  location: Westeurope
  owner:
    name: dev-magenta
  version: "8.0.21"
  sku:
    name: Standard_D4ds_v4
    tier: GeneralPurpose
  administratorLogin: psqladmin
```

Below are the api-resources installed
```
$ kubectl api-resources |grep FlexibleServer
flexibleservers                                        dbformysql.azure.com/v1beta20210501    true         FlexibleServer
flexibleserversadministrators                          dbformysql.azure.com/v1api20220101     true         FlexibleServersAdministrator
flexibleserversconfigurations                          dbformysql.azure.com/v1api20220101     true         FlexibleServersConfiguration
flexibleserversdatabases                               dbformysql.azure.com/v1beta20210501    true         FlexibleServersDatabase
flexibleserversfirewallrules                           dbformysql.azure.com/v1beta20210501    true         FlexibleServersFirewallRule
```

I also tried to replace v1beta to v1api in templates/generated/admissionregistration.k8s.io_v1_validatingwebhookconfiguration_azureserviceoperator-validating-webhook-configuration.yaml but that didnt work.
