### ISSUE TITLE
unable to set Private DNS name for FlexibleServer

### ISSUE THREAD

**Issue by amitganvir23** [Azure/azure-service-operator#3199]
I have install operator from https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator-v2.1.0.tgz and we configure workload identity

We are trying to create user but its trying to connect servername "mlflow.mysql.database.azure.com" but dont want to use this servername instead we need to use private dnsame "mlflow.dev.azcloud.amit.de"

```
$kubectl get users
NAME         READY   SEVERITY   REASON   MESSAGE
kf-u-amitg   False   Warning    Failed   failed to connect database. Server: mlflow.mysql.database.azure.com, Database: mysql, Port: 3306, AdminUser: psqladmin: error pinging the mysql db (mlflow.mysql.database.azure.com:3306/mysql): dial tcp: lookup mlflow.mysql.database.azure.com on 192.168.2.10:53: no such host

```
This is our user.yaml file

```
apiVersion: dbformysql.azure.com/v1beta1
kind: User
metadata:
  name: kf-u-amitg 
spec:
  owner:
    name: mlflow
  privileges:
    - SHOW DATABASES
  databasePrivileges:
    kf-u-amitg:
      - SELECT
      - INSERT
      - UPDATE
      - ALTER
      - CREATE
  localUser:
    serverAdminUsername: psqladmin
    serverAdminPassword:
      name: mysqlpassword
      key: password
    password:
      name: mysqlpassword
      key: password
```

This is our yaml file for flexibleserver, didnt fine any option to use fqdn name
```
kubectl create secret generic mysqlfqdn --from-literal=fullyQualifiedDomainName='dev-mlops-mlflow.dev.azcloud.telekom.de'

apiVersion: dbformysql.azure.com/v1beta20210501
kind: FlexibleServer
metadata:
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
  name: mlflow
  namespace: azureserviceoperator-system
spec:
  operatorSpec:
    secrets:
      fullyQualifiedDomainName:
        name: mysqlfqdn 
        key: fullyQualifiedDomainName
  administratorLogin: psqladmin
  azureName: mlflow
  location: Westeurope
  owner:
    name: dev-magenta
  sku:
    name: Standard_D4ds_v4
    tier: GeneralPurpose
  version: 8.0.21
```
