### ISSUE TITLE
Bug: WorkloadIdentityCredential: unable to resolve an endpoint

### ISSUE THREAD

**Issue by MikeFear** [Azure/azure-service-operator#3259]
**Version of Azure Service Operator**

mcr.microsoft.com/k8s/azureserviceoperator:v2.3.0

**Describe the bug**
We upgraded the Azure Service Operator today to version v2.3.0 on AKS and since then it seems to fail to reconcile the resources. We get a lot of errors like the following:
WorkloadIdentityCredential: unable to resolve an endpoint: server response error:\\n context deadline exceeded

`I0906 14:06:44.368706       1 common.go:58] controllers/ResourceGroupController "msg"="Reconcile invoked" "annotations"={"serviceoperator.azure.com/operator-namespace":"azureserviceoperator-system","serviceoperator.azure.com/reconcile-policy":"skip","serviceoperator.azure.com/resource-id":"/subscriptions/[REDACTED]/resourceGroups/[REDACTED]"} "conditions"="[Condition [Ready], Status = \"False\", ObservedGeneration = 1, Severity = \"Warning\", Reason = \"Failed\", Message = \"error getting status for resource ID \\\"/subscriptions/[REDACTED]/resourceGroups/[REDACTED]\\\": getting resource with ID: \\\"/subscriptions/[REDACTED]/resourceGroups/[REDACTED]\\\": WorkloadIdentityCredential: unable to resolve an endpoint: server response error:\\n context deadline exceeded\", LastTransitionTime = \"2023-09-06 09:29:09 +0000 UTC\"]" "creationTimestamp"="2023-09-06T08:05:38Z" "deletionTimestamp"=null "finalizers"=["serviceoperator.azure.com/finalizer"] "generation"=1 "kind"={"kind":"ResourceGroup","apiVersion":"resources.azure.com/v1api20200601storage"} "name"="resource-group" "namespace"="test" "owner"=null "ownerReferences"=null "resourceVersion"="306165276" "uid"="[REDACTED]"`

This happens for all kind of resources, another example:
`E0906 14:02:44.339362       1 generic_reconciler.go:361] controllers/StorageAccountsBlobServiceController "msg"="Encountered error impacting Ready condition" "error"="Reason: Failed, Severity: Warning, RetryClassification: RetrySlow, Cause: error getting status for resource ID \"/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Storage/storageAccounts/[REDACTED]/blobServices/default\": getting resource with ID: \"/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Storage/storageAccounts/[REDACTED]/blobServices/default\": WorkloadIdentityCredential: unable to resolve an endpoint: server response error:\n context deadline exceeded" "name"="cockpit" "namespace"="test"`

**To Reproduce**
- Upgrade from Azure Service Operator v2.2.0 to v2.3.0 via Helm

**Expected behavior**
Resources should still be synced successfully.

**Screenshots**

**Additional context**
We are using useWorkloadIdentityAuth: true to authenticate with Azure.
I also tried to downgrade again to v2.2.0 without success and getting the same errors.

**Comment by matthchr** [comment]
Shot in the dark here but: Are you running ASO on a free tier AKS cluster? How many CRDs are you specifying in CRDPattern? Have you seen https://azure.github.io/azure-service-operator/guide/crd-management/ - specifically [this section](https://azure.github.io/azure-service-operator/guide/crd-management/)

>  * Do not use crdPattern=* on AKS free tier clusters. It installs so many CRDs that it can overload kube-apiserver and cause restarts. See [#2920](https://github.com/Azure/azure-service-operator/issues/2920) for details. Instead, specify a crdPattern containing only the groups (or individual CRDs) you intend to use.
> * We strongly recommend including entire groups such as dbformysql.azure.com/* in crdPattern. Individual CRDs such as dbformysql.azure.com/FlexibleServer may be specified as well, but there are often other resources in the group which pair together to enable other scenarios, such as dbformysql.azure.com/FlexibleServersFirewallRules. It’s generally easier to just include the whole group.

Is the ASO pod restarting a lot as well?

**Comment by matthchr** [comment]
I could look more into your cluster if you shared the subid and rg name with me. If you don't want to do it here I'm `matthchr` on k8s Slack as well.

**Comment by matthchr** [comment]
Worked over Slack and determine that #3164 is the cause. Deletion of the policies seems to have fixed things.

We test this case in CI so I don't understand why it didn't turn this issue up. I'll revert the Helm 2.3.0 Helm chart for now.

**Comment by matthchr** [comment]
Ahh, this is probably why we didn't catch: https://github.com/kubernetes-sigs/kind/issues/842

We run our tests in `kind` and the default CNI there ignores network policies I think.

**Comment by matthchr** [comment]
Our network policy was messed up, and even if it hadn't been it was missing a rule for DNS.

Now things should work. Please try again. Sorry for the inconvenience!

**Comment by vsawant1608** [comment]
I tried this installation today on Azure Openshift cluster and it was still giving me same error.

As suggested in https://github.com/Azure/azure-service-operator/issues/3259#issuecomment-1708776198 I deleted egresss network policies and it started working.

I installed latest operator version as mentioned here https://azure.github.io/azure-service-operator/guide/authentication/credential-format/#azure-workload-identity.

Also tried created egress policies manually as per code in main branch.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: azure-service-operator-allow-egress
  namespace: azureserviceoperator-system
spec:
  egress:
  # Required for communication with DNS
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # Required for communication with the Azure API
  - ports:
    - port: 443
      protocol: TCP
  # Required for communication with the Kubernetes API
  - ports:
    - port: 6443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  # Required for communication with MySQL servers when using MySQL user object
  - ports:
    - port: 3306
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  # Required for communication with PostgreSQL servers when using PostgreSQL user object
  - ports:
    - port: 5432
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Egress
```

#matthchr as per last comment issue is fixed. Any idea why it might be occuring on azure redhat openshift cluster?
