### ISSUE TITLE
Improve Resource Status Messages Upon Failure

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#3322]
**Describe the current behavior**
When a resource creation fails, ASO exposes the last status Azure provides, which might not be informative.

E.g.
CosmosDB provisioning failed due to capacity constraints.

```yaml
Status:
  Conditions:
    Last Transition Time:  2023-09-19T00:21:23Z
    Message:               DatabaseAccount XXXXXXX is in a failed provisioning state because the previous attempt to create it was not successful. Please delete the previous instance before attempting to recreate this account.
ActivityId: 00000000-0000-0000-0000-000000000000, Microsoft.Azure.Documents.Common/2.14.0: PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/XXXXXXX/providers/Microsoft.DocumentDB/databaseAccounts/XXXXXXX
--------------------------------------------------------------------------------
RESPONSE 400: 400 BadRequest
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "message": "DatabaseAccount XXXXXXX is in a failed provisioning state because the previous attempt to create it was not successful. Please delete the previous instance before attempting to recreate this account.\r\nActivityId: 00000000-0000-0000-0000-000000000000, Microsoft.Azure.Documents.Common/2.14.0"
}
--------------------------------------------------------------------------------
```

<img width="2213" alt="Screenshot 2023-09-19 at 11 09 35 AM" src="https://github.com/Azure/azure-service-operator/assets/8487757/55894c8d-34e9-40df-a6c1-f2dcf564a8c9">

This message provides clear instructions for re-creating the DatabaseAccount, while the earlier message in close proximity exposes another reason for the failure:

<img width="2209" alt="Screenshot 2023-09-19 at 11 09 24 AM" src="https://github.com/Azure/azure-service-operator/assets/8487757/72e89637-c20c-4e95-acbd-cd93e26b209e">

**Describe the improvement**
To group events occurring within a ~5-minute proximity and extend status messages to provide more details, add an event category.

**Additional context**
I've encountered these issues not only with CosmosDB but also with different Azure objects.
