### ISSUE TITLE
Unable to create managed identity

### ISSUE THREAD

**Issue by shalinin00** [Azure/azure-service-operator#3381]
Facing below issue related to Managed identity creation - 

**Problem Statement** - Trying to create managed identity, federated identity for provisioning Flexible server through ASO v2 operator. Managed identity is throwing following error after creating federated identity. Managed identity should use secrete and service account from dev namespace but its using service account from azureserviceoperator-system namespace.

**Steps to reproduce** -
 1. Create managed identity. Succeeded but started failing after creating federated identity.
     Error -
```
POST https://login.microsoftonline.com/<ID>/oauth2/v2.0/token
--------------------------------------------------------------------------------
RESPONSE 401 Unauthorized
--------------------------------------------------------------------------------
{
 "error": "invalid_client",
 "error_description": "AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: <OIDC url>. Assertion Subject: 'system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace ID: <some ID>\r\nCorrelation ID: <ID>\r\nTimestamp: 2023-10-05 02:46:28Z",
```
 2. Create federated identity.
     Error -
 ` Group/Kind: managedidentity.azure.com/UserAssignedIdentity" cannot be found. Progress is blocked until the owner is created.`

**Currently following is my setup** -
 1. I’ve GLOBAL secret and service account created in azureserviceoperator-system namespace -
 2. I’ve secret and service account created in dev namespace- which I used to create Managed Identity.

```
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: test-user-identity
  namespace: dev
spec:
  location: useast
  owner:
    name: aso-rg-test
  operatorSpec:
    configMaps:
      tenantId:
        name: admin-test
        key: tenantId
      clientId:
        name: admin-test
        key: clientId

```

```
apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: aso-fic
  namespace: dev
spec:
  owner:
    name: test-user-identity
  audiences:
    # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  issuer: <OIDC URL>
  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:dev:azureserviceoperator-default

```

**Comment by matthchr** [comment]
This seems somewhat duplicate to the question you asked on #3344, but answering here as well:

> Currently following is my setup -
> 1. I’ve GLOBAL secret and service account created in azureserviceoperator-system namespace -
> 2. I’ve secret and service account created in dev namespace- which I used to create Managed Identity.

your item 1 makes perfect sense.
Item 2, you don't need another service account. ASO always uses its service account. what you need is a different secret, but the _same_ service account.

So your federated identity credential for item 2 should look like:

```
apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: aso-fic
  namespace: dev
spec:
  owner:
    name: test-user-identity
  audiences:
    # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  issuer: <OIDC URL>
  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default
```

Think of it like this: the `system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default` is the identity in Kubernetes _of ASO_. You need to give access to ASO, to use the `test-user-identity` UMI from the `dev` namespace.

To do this, you must:
1. Create the `test-user-identity` in the `dev` namespace (you've already done this).
2. Export the client-id and tenant-id of `test-user-identity` to a configMap in the `dev` namespace (you've already done this)
3. Tell Azure that ASO is allowed to impersonate this identity in AAD. This is what the `FederatedIdentityCredential` is for, but you've told it that ServiceAccount `system:serviceaccount:dev:azureserviceoperator-default` has that permission. ASO doesn't use `system:serviceaccount:dev:azureserviceoperator-default` it uses `system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default`, hence the error from AAD.

If you correct your step 3, it should work.
