### ISSUE TITLE
Feature: expose SignalR credentials

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#3406]
Feature: expose SignalR credentials: keys and connection strings 

Azure Service Operator version: 2
apiVersion: signalrservice.azure.com/v1api20211001
kind: SignalR

Please consider adding operatorSpec to the SignalR
```
  operatorSpec:
    secrets:
      key1:
        name: signalrsecret
        key: key1
      key2:
        name:  signalrsecret
        key: key2
      ConnectionString1:
        name: signalrsecret
        key: ConnectionString1
      ConnectionString2:
        name:  signalrsecret
        key: ConnectionString2
```
