### ISSUE TITLE
Documentation says uninstalling chart uninstalls CRDs, but it does not

### ISSUE THREAD

**Issue by antoineozenne-at-leocare** [Azure/azure-service-operator#3416]
**Version of Azure Service Operator**
2.3.0

**Describe the bug**
When uninstalling the chart, the CRD are not uninstalled (contrary to what the documentation indicates).

**To Reproduce**

* Install the chart with the following commands:

   ```sh
   kubectl create namespace azureserviceoperator-system --dry-run=client -o yaml | kubectl apply -f -
   helm upgrade --install --namespace azureserviceoperator-system azureserviceoperator-system aso2/azure-service-operator --version 2.3.0 --values myvalues.yaml
   ```

   The `myvalues.yaml` content is the following:

   ```yaml
   azureSubscriptionID: xxx
   azureTenantID: xxx
   azureClientID: xxx
   useWorkloadIdentityAuth: true
   crdPattern: 'managedidentity.azure.com/*;authorization.azure.com/*'
   ```

* Deploy some resources.
* Delete these resources.
* Uninstall the chart with the following commands:

   ```sh
   helm uninstall --namespace azureserviceoperator-system azureserviceoperator-system
   kubectl delete namespace azureserviceoperator-system
   ```

* See the CRD are always here:

   ```sh
   kubectl api-resources | grep azure.com
   # roleassignments                                       authorization.azure.com/v1api20200801preview     true         RoleAssignment
   # federatedidentitycredentials                          managedidentity.azure.com/v1api20220131preview   true         FederatedIdentityCredential
   # userassignedidentities                                managedidentity.azure.com/v1beta20181130         true         UserAssignedIdentity
   ```

**Expected behavior**
All the CRD are uninstalled.
