### ISSUE TITLE
RoleAssignment CRD owner armId allows privilege escalation.

### ISSUE THREAD

**Issue by Roman-Galeev** [Azure/azure-service-operator#3645]
Currently it's possible to grant access to arbitrary resource in subscription by setting up owner.armId and Contributor role:

```yaml
spec:
  owner:
    armId: /subscriptions/00000000-0000-0000-0000-000000000000
  roleDefinitionReference:
    armId: /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c
```
I believe RoleAssignment should be scoped to namespace only by disallowing armId field in owner, and we also need a ClusterRoleAssignment CRD which can refere to owners in different namespaces and allow armId field.
