### ISSUE TITLE
StorageAccount networkAcls does NOT allow CIDR notation

### ISSUE THREAD

**Issue by aaguilartablada** [Azure/azure-service-operator#3647]
**Version of Azure Service Operator**
2.5.0
CRD:
  - Kind: StorageAccount
  - ApiVersion: storage.azure.com/v1api20230101

**Describe the bug**

Error when configuring ipRules for Storage networkAcls using CIDR notation.

**To Reproduce**

When configuring ipRules everything goes OK when setting IPs as follow:

```
  networkAcls:
    bypass: AzureServices
    defaultAction: Deny
    ipRules:
    - action: Allow
      value: 1.1.1.1
    - action: Allow
      value: 2.2.2.2
```

But it fails when using CIDR notation. For example, with this configuration:

```
  networkAcls:
    bypass: AzureServices
    defaultAction: Deny
    ipRules:
    - action: Allow
      value: 1.1.1.0/24
    - action: Allow
      value: 2.2.2.0/24
```

> quoting CIDR doesn't work

ASO shows this error: 

```
      {
        "error": {
          "code": "InvalidValuesForRequestParameters",
          "message": "Values for request parameters are invalid: networkAcls.ipRule[*].value. For more information, see - https://aka.ms/storagenetworkruleset"
        }
      }
```

Going to the URL solves nothing, as it says I can use CIDR notation
