### ISSUE TITLE
Support RoleAssignments to Kubernetes Namespaces (managedClusters/<>/namespaces/<ns>)

### ISSUE THREAD

**Issue by kdandersen** [Azure/azure-service-operator#3670]
Hi all, 
hope it is OK to ask a question here. 

I have searched “half the Internet”, the ASO2 documentation and also tried to see if a ASO2 Slack channel exists – with no avail.

I am trying to use ASO2 in a use case to deliver AKS Namespaces incl RBAC as a combination Kubernetes managed objects/CRDs such as ‘UserAssignedIdentity’ and ‘FederatedIdentityCredential’ objects for Namespace Service Account federated identities. And this works fine.

But I am also trying to use the ‘RoleAssignment’ CRD to grant access for users/groups at a Kubernetes Namespace scope, and I can’t see if this is at all possible.

Note, the AKS cluster is not a ASO2 managed/created object.

I would like to create the equivalent to the following AZ CLI configuration:

```
az role assignment create --role "Azure Kubernetes Service RBAC Writer" --assignee <principal_object_id> \
 --scope /subscriptions/<subscriptio_id>/resourceGroups/<resource_group>/providers/Microsoft.ContainerService/managedClusters/<aks_name>/namespaces/<namespace_name>
```
I have been able to make the ‘RoleAssignment’ work on a scope that is a ASO2 “managed” resource (Resource Group). See examples code below.

But is it at all possible to reference a ‘scope’ that isn’t known to or managed by ASO2 CRDs, as can be seen in the AZ CLI example?

**EDIT:**
I actually managed to make this work by getting a hint from issue 3645
https://github.com/Azure/azure-service-operator/issues/3645

By making the 
```
  owner:
    armId: /subscriptions/<subscriptio_id>/resourceGroups/<resource_group>/providers/Microsoft.ContainerService/managedClusters/<aks_name>/namespaces/<namespace_name>

```
This created the role assignment at of the 'Azure Kubernetes Service RBAC Writer' at the namespace scope of a referenced AKS cluster.

Kind regards
Kim

```
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: <rg_name>
  namespace: <aso_namespace>
  annotations: 
    serviceoperator.azure.com/reconcile-policy: skip
spec:
  location: <az_region>
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: aso2-demo-ra
  namespace: <aso_namespace>
spec:
  # This resource can be owner by any resource. In this example we've chosen a resource group for simplicity
  owner:
    name: <rg_name>
    group: resources.azure.com
    kind: ResourceGroup
  # This is the Principal ID of the AAD identity to which the role will be assigned
  # Example Azure EntraID Group
  principalId: <group_object_id>
  principalType: Group
  roleDefinitionReference:
    # 4d97b98b-1d4f-4787-a291-c67834d212e7 represents 'Network Contributor'
    armId: /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7
```
