### ISSUE TITLE
Include system affinity for when ASO runs on AKS

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3828]
**Describe the improvement**

A suggestion made via email:

> My suggestion to improve ASO would be to include the following node affinity block that would target system nodepools on any AKS cluster:

``` yaml
affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: In
              values:
                - system
```

According to @matthchr we shouldn't use `required` because it ASO is supported on non AKS clusters, but there's a `preferredDuringSchedulingIgnoredDuringExecution` we could use too.
