### ISSUE TITLE
Bug: unable to set only workspaceResourceReference for ContainerGroup

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-service-operator#4046]
**Version of Azure Service Operator**
2.7.0

**Describe the bug**
According to the spec, it should be possible to reference existing Workspace resource using `workspaceResourceReference` for ContainerGroup but validation requires `workspaceId` and `workspaceKey` to be [set](https://github.com/Azure/azure-service-operator/blob/main/v2/api/containerinstance/v1api20211001/container_group_types_gen.go#L8325-L8331).

**To Reproduce**
```yaml
---
apiVersion: operationalinsights.azure.com/v1api20210601
kind: Workspace
metadata:
  name: sampleworkspace
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standalone
---
apiVersion: containerinstance.azure.com/v1api20211001
kind: ContainerGroup
metadata:
  name: samplecontainergroup
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  containers:
    - name: samplecontainergroup
      image: mcr.microsoft.com/azuredocs/aci-helloworld
      ports:
        - protocol: TCP
          port: 80
      resources:
        requests:
          cpu: 1
          memoryInGB: 2
  diagnostics:
    logAnalytics:
      logType: ContainerInsights
      workspaceResourceReference:
        group: operationalinsights.azure.com
        kind: Workspace
        name: sampleworkspace
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
      - protocol: TCP
        port: 80
```

**Expected behavior**
Container group to be successfully created

**Actual behaviour**
error: error validating error validating data: [ValidationError(ContainerGroup.spec.diagnostics.logAnalytics): missing required field "workspaceId" in com.azure.containerinstance.v1api20211001.ContainerGroup.spec.diagnostics.logAnalytics, ValidationError(ContainerGroup.spec.diagnostics.logAnalytics): missing required field "workspaceKey" in com.azure.containerinstance.v1api20211001.ContainerGroup.spec.diagnostics.logAnalytics];
