### ISSUE TITLE
Question  ManagedCluster - Can credential for Windows & Linux node be passed as secret instead of plain text

### ISSUE THREAD

**Issue by RSE132** [Azure/azure-service-operator#4088]
Can credential for Windows & Linux node be passed as secret instead of plain text ?

**Current supported**
```
# Linux node public key profile
      linuxProfile:
        adminUsername: "azureuser"
        ssh:
          publicKeys:                                        # SSH Key for node
          - keyData: |
              ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# Windows node credential profile
      windowsProfile:
        adminUsername: "azureuser"
        adminPassword: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**Expectation**

```
# Linux node public key profile
      linuxProfile:
        adminUsername: "azureuser"
        ssh:
          publicKeys:                                        # SSH Key for node
          - keyData:
               secret:
                  key:
                  value:
# Windows node credential profile
      windowsProfile:
        adminUsername: "azureuser"
        adminPassword:
           secret:
              key:
              value:

```
