### ISSUE TITLE
Bug: ApplicationGateway CRD's sslCertificates is not picked from kubernetes Secret

### ISSUE THREAD

**Issue by SundarMunichamy** [Azure/azure-service-operator#4112]
**ASO V2 2.7.0 **

**Describe the bug**
ApplicationGateway CRD's sslCertificates is not picked from kubernetes Secret.

I am creating application gateway via ASO V2 operator and trying to attach the kubernetes secret containining the SSL certificates in pfx format.  The certificate is password protected. 

Piece of code :

``` yaml
  sslCertificates:
    - name: my-pfx-secret
      data:
        name: my-pfx-secret
        key: cert.pfx
      password:
        key: password
        name: my-pfx-secret-pwd
```

[appgw.txt](https://github.com/user-attachments/files/15901171/appgw.txt)

  ( Attached the application gateway Custom resource yaml file )
    
  
**To Reproduce**
1) Create the application gateway via the ASO v2
2) Create the k8s secret in the same namespace with ssl certificate as pfx format .
3) Create another k8s secret or same secret with password details and point in the custom resource.

**Expected behavior**
SSL certificate should be attached to application gateway in the pfx format

**Screenshots**

**Additional context**
