### ISSUE TITLE
Feature: Virtual Network Link for DnsForwardingRuleset 

### ISSUE THREAD

**Issue by vronnG** [Azure/azure-service-operator#4234]
**Describe the current behavior**
[DnsForwardingRuleset](https://azure.github.io/azure-service-operator/reference/network/v1api20220701/#network.azure.com/v1api20220701.DnsForwardingRuleset)
- How to link virtual network to forwarding ruleset ?
  - Similar to [PrivateDnsZonesVirtualNetworkLink](https://azure.github.io/azure-service-operator/reference/network/v1api20200601/#network.azure.com/v1api20200601.PrivateDnsZonesVirtualNetworkLink)
 

Similar to how we do it azure portal:
<img width="802" alt="Screenshot 2024-08-29 at 1 57 12 PM" src="https://github.com/user-attachments/assets/a3d46d43-ed69-44e8-8e31-911359f3a7ae">
and 
https://learn.microsoft.com/en-us/azure/templates/microsoft.network/dnsforwardingrulesets/virtualnetworklinks?pivots=deployment-language-arm-template

Should be able to link virtual network
```
---
apiVersion: network.azure.com/v1api20220701
kind: DnsForwardingRuleset
metadata:
  creationTimestamp: null
  name: xx
spec:
  azureName: xx
  dnsResolverOutboundEndpoints:
  - reference:
      armId: /subscriptions/XXXXXXX/resourceGroups/XX/providers/Microsoft.Network/dnsResolvers/xx/outboundEndpoints/xx
  location: westus3
```

**Describe the improvement**
Able to link DNS Forwarding Ruleset with Virtual Network
