### ISSUE TITLE
Bug: Asterisk ‘*’ is causing issue when passed as a value for destinationPortRange in NetworkSecurityGroupsSecurityRule

### ISSUE THREAD

**Issue by nishant221** [Azure/azure-service-operator#4246]
**Version of Azure Service Operator**

mcr.microsoft.com/k8s/azureserviceoperator:v2.8.0

**Describe the bug**

According to [NetworkSecurityGroupsSecurityRule](https://azure.github.io/azure-service-operator/reference/network/v1api20201101/#network.azure.com/v1api20201101.NetworkSecurityGroupsSecurityRule) , asterisk ‘*’ 
should be allowed as a value for `destinationPortRange`. But when the same is passed it's causing following error:

<img width="1695" alt="image" src="https://github.com/user-attachments/assets/a5761cd5-7657-4686-9308-9fc3adbc6e0f">

**To Reproduce**

- Pass following objects to ASO via kubectl

```
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
  name: test-rg
spec:
  azureName: test-rg
  location: eastus2
---
apiVersion: network.azure.com/v1api20201101
kind: NetworkSecurityGroup
metadata:
  name: nsg-test
spec:
  location: eastus2
  owner:
    name: test-rg
---
apiVersion: network.azure.com/v1api20201101
kind: NetworkSecurityGroupsSecurityRule
metadata:
  name: nsg-test-0
spec:
  azureName: test_rule
  owner:
    name: nsg-test
  priority: 2000
  sourcePortRange: "*"
  destinationPortRange: "*"
  sourceAddressPrefix: "VirtualNetwork"
  destinationAddressPrefix: "*"
  access: Deny
  protocol: "*"
  direction: Outbound
  description: Deny egress connections by default
``` 

**Expected behavior**
NSG should be created with required rules.

**Screenshots**

**Additional context**
