### ISSUE TITLE
Bug: Passing multiple values to "bypass" parameter is not working for NetworkRuleSet  while creation of storage account

### ISSUE THREAD

**Issue by nishant221** [Azure/azure-service-operator#4247]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.8.0

**Describe the bug**
While configuring  `NetworkRuleSet` of StorageAccount, we are trying to pass multiple values to "bypass"  parameter. The behaviour we are observing is that only the first value gets applied and rest of the values are ignored. The documentation says that multiple values can be passed separated by comma but it's not working as expected.

**To Reproduce**

```
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: test-rg
spec:
  azureName: test-rg
  location: eastus2
---
apiVersion: storage.azure.com/v1api20230101
kind: StorageAccount
metadata:
  name: test-stg-account
spec:
  kind: Storage
  allowBlobPublicAccess: false
  allowCrossTenantReplication: false
  azureName: teststgaccont
  location: eastus2
  sku:
    name: Standard_LRS
    tier: Standard
  supportsHttpsTrafficOnly: true
  owner:
    name: test-rg
  networkAcls:
    bypass: "Logging,Metrics,AzureServices"    # Only first value gets applied and rest two are ignored
    defaultAction: Deny
```

**Expected behavior**

We should be able to pass multiple values to `bypass` parameter.

**Screenshots**

**Additional context**
