### ISSUE TITLE
Bug: Unable to set user assigned managed identity on storage accounts

### ISSUE THREAD

**Issue by nraooptum** [Azure/azure-service-operator#4325]
**Version of Azure Service Operator**
latest (experimental)

**Describe the bug**
We are unable to associate a managed identity to the storage account. We get the following error back from the provider:

```
RESPONSE 400: 400 Bad Request

        ERROR CODE: InvalidValuesForRequestParameters

        --------------------------------------------------------------------------------

        {
          "error": {
            "code": "InvalidValuesForRequestParameters",
            "message": "Values for request parameters are invalid: properties.encryption.identity."
          }
        }
```

**To Reproduce**

```
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: neil-cdk8s-test-storage-uami
  namespace: xxx
spec:
  azureName: xxx
  location: centralus
  operatorSpec:
    configMaps:
      clientId:
        key: clientId
        name: neil-cdk8s-test-storage-uami
      principalId:
        key: principalId
        name: neil-cdk8s-test-storage-uami
  owner:
    name: xxx
  tags:
    Contact: xxx
---
apiVersion: authorization.azure.com/v1api20200801preview
kind: RoleAssignment
metadata:
  name: xxx
  namespace: xxx
spec:
  owner:
    armId: >-
      /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.KeyVault/vaults/xxx
  principalIdFromConfig:
    key: principalId
    name: neil-cdk8s-test-storage-uami
  roleDefinitionReference:
    armId: >-
      /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/4633458b-17de-408a-b874-0445c86b69e6
---
apiVersion: storage.azure.com/v1api20210401
kind: StorageAccount
metadata:
  name: xxx
  namespace: xxx
spec:
  accessTier: Hot
  allowBlobPublicAccess: false
  allowCrossTenantReplication: false
  allowSharedKeyAccess: false
  azureName: xxx
  encryption:
    identity:
      userAssignedIdentityReference:
        group: managedidentity.azure.com
        kind: UserAssignedIdentity
        name: neil-cdk8s-test-storage-uami
    keySource: Microsoft.Keyvault
    keyvaultproperties:
      keyname: xxx
      keyvaulturi: https://xxx.vault.azure.net
    requireInfrastructureEncryption: true
    services:
      blob:
        enabled: true
        keyType: Account
  isHnsEnabled: false
  isNfsV3Enabled: false
  kind: StorageV2
  largeFileSharesState: Disabled
  location: centralus
  minimumTlsVersion: TLS1_2
  networkAcls:
    bypass: AzureServices
    defaultAction: Deny
  operatorSpec:
    configMaps:
      blobEndpoint:
        key: blob-endpoint
        name: neil-cdk8s-test-storage
  owner:
    armId: >-
      /subscriptions/xxx/resourceGroups/xxx
  sku:
    name: Standard_GRS
    tier: Standard
  supportsHttpsTrafficOnly: true
  tags:
    Contact: xxx
```

**Expected behavior**
Storage account with UAMI should get created.

**Additional context**
This seems to be the same error as once seen in the [terraform azurerm](https://github.com/hashicorp/terraform-provider-azurerm/issues/16374) provider.
