### ISSUE TITLE
Feature: Support DBforPostgreSQL FlexibleServer to configure entra auth

### ISSUE THREAD

**Issue by Paul-B98** [Azure/azure-service-operator#4331]
It would be helpful to not only have the option to specify if the Entra authentication (`spec.authConfig.activeDirectoryAuth: Enabled`) is enabled on the `FlexibleServer` (PostgreSQL) but also what object ids are administrators.

A solution could be a list of ids as part of the authConfig:

```yaml
spec:
  authConfig: 
    activeDirectoryAuth: Enabled
    objectID:
    - 00000000-0000-0000-0000-000000000000
    - ...
```
