### ISSUE TITLE
Bug: Unable to import any resources from Insights version 2021-05-01-preview

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#4337]
## Describe the bug

When trying to import a new resource from Microsoft.Insights, the Load Types stage of the generator crashes with a panic. This is the error from the start of the panic (formatted for readability):

``` 
error generating code: 
failed to execute stage 1: Load all types from Swagger files: 
panic: 
While merging file /workspaces/azure-service-operator/v2/specs/azure-rest-api-specs/specification/monitor/resource-manager/Microsoft.Insights/preview/2021-05-01-preview/subscriptionDiagnosticsSettings_API.json: 
duplicate resource types generated
```

## To Reproduce

Add this to the `objectModelConfiguration` section for `insights`:

``` yaml
    2021-05-01-preview:
      DiagnosticSetting:
        $export: true
        $supportedFrom: v2.10.0
```

Also add this to the `typeFilters` (to allow the new preview version to be _seen_):

``` yaml
  - action: include
    group: insights
    version: v*20210501preview
    because: We're using DiagnosticSetting from this.
```

## Expected behavior

The specified resource should be imported.

If any error occurs, the error message should be useful to an end user.

## Additional context

Error reported [via Slack](https://kubernetes.slack.com/archives/C046DEVLAQM/p1727951816125199).
