### ISSUE TITLE
Bug: Loadbalancer doesn't find and attach the ip's address to the backendAddressPools

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-service-operator#4368]
**Version of Azure Service Operator**

**Describe the bug**
A backend for the loadbalancer object is created but the vnet and ip configs are not wired up properly:

```
apiVersion: network.azure.com/v1api20201101
kind: LoadBalancer
metadata:
  creationTimestamp: null
  name: capz-public-lb
  annotations:
    serviceoperator.azure.com/credential-from: capz-conf-a6xnyi-aso-secret
    serviceoperator.azure.com/operator-namespace: capz-system
spec:
  owner: 
    name: capz-conf-a6xnyi
  azureName: capz-conf-public-lb
  backendAddressPools:
  - loadBalancerBackendAddresses:
    - name: capz-conf-a6xnyi-control-plane-jhq22
      virtualNetwork: 
        reference:
          armId: /subscriptions/subid/resourceGroups/capz-conf-a6xnyi/providers/Microsoft.Network/virtualNetworks/capz-conf-a6xnyi-vnet
      subnet:
        reference:
          armId: /subscriptions/subid/resourceGroups/capz-conf-a6xnyi/providers/Microsoft.Network/virtualNetworks/capz-conf-a6xnyi-vnet/subnets/control-plane-subnet
      ipAddress: "10.255.0.4"
    name: capz-conf-public-lb-backendPool
.... more config
```

**To Reproduce**
<Fill in the steps>

**Expected behavior**

A backend should adopt the IP address into its backend pool

**Screenshots**

you can see the backend got created but no ip addresses were adopted (notice the vnet info is missing but was provided):
![Image](https://github.com/user-attachments/assets/0f22bbcd-12eb-497e-9da7-7080a51ad488)
![Image](https://github.com/user-attachments/assets/e526fd64-c0f3-4aef-94a0-6228867a189b)

**Additional context**
it should look like:

![Image](https://github.com/user-attachments/assets/49a9c0df-0282-4904-8f2b-af6791d45c21)
