### ISSUE TITLE
Bug: asoctl-imported AKS resource has no spec.owner field

### ISSUE THREAD

**Issue by arsdragonfly** [Azure/azure-service-operator#4564]
## Describe the bug

asoctl-imported AKS resource has no owner field.

Sample output:

```
zheyushen@DESKTOP-2VRVE78:~$ ./asoctl import azure-resource /subscriptions/02a122b3-ea01-470f-98eb-cfe7780e2b47/resourceGroups/zheyuslinkyrg/providers/microsoft.containerservice/managedClusters/zheyuslinky2
16:39:03 INF Imported kind=ManagedCluster.containerservice.azure.com name=zheyuslinky2
16:39:25 INF Successful imports Count=1 Group=containerservice.azure.com Kind=ManagedCluster
```
```yaml
---
apiVersion: containerservice.azure.com/v1api20240901
kind: ManagedCluster
metadata:
  creationTimestamp: null
  name: zheyuslinky2
spec:
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: false
    azurepolicy:
      enabled: false
    omsAgent:
      config:
        logAnalyticsWorkspaceResourceID: /subscriptions/02a122b3-ea01-470f-98eb-cfe7780e2b47/resourcegroups/DefaultResourceGroup-EUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-02a122b3-ea01-470f-98eb-cfe7780e2b47-EUS
        useAADAuth: "true"
      enabled: true
  agentPoolProfiles:
  - count: 2
    enableAutoScaling: true
    enableFIPS: false
    enableNodePublicIP: false
    kubeletDiskType: OS
    maxCount: 5
    maxPods: 110
    minCount: 2
    mode: System
    name: agentpool
    orchestratorVersion: 1.30.7
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: Ubuntu
    osType: Linux
    powerState:
      code: Running
    securityProfile:
      enableSecureBoot: false
      enableVTPM: false
    type: VirtualMachineScaleSets
    upgradeSettings:
      maxSurge: 10%
    vmSize: Standard_D2as_v6
  autoScalerProfile:
    balance-similar-node-groups: "false"
    daemonset-eviction-for-empty-nodes: false
    daemonset-eviction-for-occupied-nodes: true
    expander: random
    ignore-daemonsets-utilization: false
    max-empty-bulk-delete: "10"
    max-graceful-termination-sec: "600"
    max-node-provision-time: 15m
    max-total-unready-percentage: "45"
    new-pod-scale-up-delay: 0s
    ok-total-unready-count: "3"
    scale-down-delay-after-add: 10m
    scale-down-delay-after-delete: 10s
    scale-down-delay-after-failure: 3m
    scale-down-unneeded-time: 10m
    scale-down-unready-time: 20m
    scale-down-utilization-threshold: "0.5"
    scan-interval: 10s
    skip-nodes-with-local-storage: "false"
    skip-nodes-with-system-pods: "true"
  autoUpgradeProfile:
    nodeOSUpgradeChannel: NodeImage
    upgradeChannel: patch
  azureMonitorProfile:
    metrics:
      enabled: true
      kubeStateMetrics:
        metricAnnotationsAllowList: ""
        metricLabelsAllowlist: ""
  azureName: zheyuslinky2
  disableLocalAccounts: false
  dnsPrefix: zheyuslinky2-dns
  enableRBAC: true
  identity:
    type: SystemAssigned
  identityProfile:
    kubeletidentity:
      clientId: 1d8cd124-7550-40d2-98da-bbc18b0d16fc
      objectId: 2c74c7a2-4673-4842-b254-74383177978c
      resourceReference:
        armId: /subscriptions/02a122b3-ea01-470f-98eb-cfe7780e2b47/resourcegroups/MC_zheyuslinkyrg_zheyuslinky2_westus3/providers/Microsoft.ManagedIdentity/userAssignedIdentities/zheyuslinky2-agentpool
  kubernetesVersion: 1.30.7
  location: westus3
  metricsProfile:
    costAnalysis:
      enabled: false
  networkProfile:
    dnsServiceIP: 10.0.0.10
    ipFamilies:
    - IPv4
    loadBalancerProfile:
      backendPoolType: NodeIPConfiguration
      effectiveOutboundIPs:
      - reference:
          armId: /subscriptions/02a122b3-ea01-470f-98eb-cfe7780e2b47/resourceGroups/MC_zheyuslinkyrg_zheyuslinky2_westus3/providers/Microsoft.Network/publicIPAddresses/6b83a45f-9dee-45b1-8b00-1e6341893be2
      managedOutboundIPs:
        count: 1
    loadBalancerSku: standard
    networkDataplane: azure
    networkPlugin: azure
    networkPluginMode: overlay
    networkPolicy: none
    outboundType: loadBalancer
    podCidr: 10.244.0.0/16
    podCidrs:
    - 10.244.0.0/16
    serviceCidr: 10.0.0.0/16
    serviceCidrs:
    - 10.0.0.0/16
  nodeResourceGroup: MC_zheyuslinkyrg_zheyuslinky2_westus3
  oidcIssuerProfile:
    enabled: true
  securityProfile:
    imageCleaner:
      enabled: true
      intervalHours: 168
    workloadIdentity:
      enabled: true
  servicePrincipalProfile:
    clientId: msi
  sku:
    name: Base
    tier: Free
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  supportPlan: KubernetesOfficial
  windowsProfile:
    adminUsername: azureuser
    enableCSIProxy: true
  workloadAutoScalerProfile: {}
---
```

## Expected behavior

generated YAML should have owner field, otherwise #3270 occurs.

## To Reproduce

create an AKS cluster, then try to use `asoctl import azure-resource`.
