### ISSUE TITLE
Bug: cdn.azure.com kind: AfdCustomDomain - crd fails for existing object

### ISSUE THREAD

**Issue by WawRepo** [Azure/azure-service-operator#4580]
### Current behavior

When creating existing domain like:
```
apiVersion: cdn.azure.com/v1api20230501
kind: AfdCustomDomain
metadata:
  name: aso-sample-custdomain
  namespace: default
  annotations:
    serviceoperator.azure.com/reconcile-policy: "detach-on-delete"
spec:
  owner:
    name: my-fd
  hostName: example.com
```

I am getting such error

   "message": "We couldn't create your custom domain. Another custom domain with the same host name already exists."     

                                                                                                                                                  
## Expected behavior

Same as for existing objects, crds are created ex. like 

```
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: some-rg
  namespace: default
  annotations:
    serviceoperator.azure.com/reconcile-policy: "detach-on-delete"
spec:
  location: westeurope

```
