### ISSUE TITLE
Bug: Getting Internal Server Error when creating Azure RedHat OpenShift cluster

### ISSUE THREAD

**Issue by braghettos** [Azure/azure-service-operator#4601]
## Describe the bug

_Please give a clear description of what you see and why you think it is a bug._

I'm trying to create a Kind: OpenShiftCluster but I'm getting in the status the following error:

```
status:
  conditions:
  - lastTransitionTime: "2025-02-27T14:58:44Z"
    message: |
      Internal server error.: PUT https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/openshiftcluster-4-15-35/providers/Microsoft.RedHatOpenShift/openShiftClusters/openshiftcluster-4-15-35
      --------------------------------------------------------------------------------
      RESPONSE 500: 500 Internal Server Error
      ERROR CODE: InternalServerError
      --------------------------------------------------------------------------------
      {
        "error": {
          "code": "InternalServerError",
          "message": "Internal server error."
        }
      }

      --------------------------------------------------------------------------------
    observedGeneration: 1
    reason: InternalServerError
    severity: Warning
    status: "False"
    type: Ready

```
Azure Service Operator Version: _What version of ASO are you using?_

version=2.12.0

mcr.microsoft.com/k8s/azureserviceoperator:v2.12.0

## Expected behavior

_A concise description of what you expected to happen._

I'm looking for a more explicit error. In pod log there is no more info than the previous status.

## To Reproduce

_Describe the steps to recreate the issue._

Apply the Custom Resource:

```
apiVersion: redhatopenshift.azure.com/v1api20231122
kind: OpenShiftCluster
metadata:
  name: openshiftcluster-4-15-35
spec:
  owner:
    name: openshiftcluster-4-15-35
  location: "northeurope"
  clusterProfile:
    version: "4.15.35"
    domain: openshiftcluster-4-15-35
    resourceGroupId: /subscriptions/<subscription-id>/resourceGroups/openshiftcluster-4-15-35-cluster
    fipsValidatedModules: Disabled
  masterProfile:
    vmSize: Standard_D8s_v3
  workerProfiles:
  - count: 1
    diskSizeGB: 128
    name: worker
    vmSize: Standard_D4s_v3
  servicePrincipalProfile:
    clientId: <client-id>
    clientSecret:
      key: AZURE_CLIENT_SECRET
      name: aso-credential
```

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Additional context

_Add any other context about the problem here._
