### ISSUE TITLE
Bug: APIM API CRD Revision support issue

### ISSUE THREAD

**Issue by anandpatra18** [Azure/azure-service-operator#4605]
## Describe the bug
Issue face while trying to create API revision using the API CRD
When we try to create multiple revision of the same API using crd the revision with active flag 'true' is the only one that appears on APIM and the revision id is always 1 irrespective of the revision id we provide in the CRD
We are not able to deploy and see a revision with active flag 'false' as the CRD does nothing about it even though it shows to be successful on the Operator level and the CRD object is in success state.

## Expected behavior

We should be able to create multiple revisions of a API using the crd and mange it with the active flag and revision id attributes of the CRD

## To Reproduce

Use the CRD to create multiple revisions , 

## Screenshots

No error hence no screenshots to share atm.

**Comment by theunrepentantgeek** [comment]
Can you supply a redacted copy of your YAML, or reference us to a sample or demo for your scenario? We're not experts in the APIM area and this would help us understand the problem you're experiencing.

**Comment by theunrepentantgeek** [comment]
@tomkerkhove Do you have any insights here?

**Comment by tomkerkhove** [comment]
No I do not, sorry. Have not heard any issues.

**Comment by anandpatra18** [comment]
I will try to add some examples once i get some time to reproduce this

**Comment by anandpatra18** [comment]
I tried creating the below 2 resource in order , once i apply the second one only that exists in the portal and only with revision id as 1 and active flag as true even the values mentioned is 2 and active flag is false

1st Resource apply:
apiVersion: apimanagement.azure.com/v1api20220801
kind: Api
metadata:
  name: test-api-revision-1
  namespace: grandcentral
spec:
  apiRevision: "1"
  apiRevisionDescription: "test revision 2"
  description: API Testing for revsion 1
  apiType: http
  displayName: test-api-revision-1
  format: swagger-json
  isCurrent: true
  owner:
    armId: "/subscriptions/2e46XXXXXXXX7a52cd1/resourceGroups/rg-XXXX-compute-dev/providers/Microsoft.ApiManagement/service/apim-XXX-dev"
  protocols: 
    - https
  value: 
  path: test/v1/poc
  subscriptionKeyParameterNames:
    header: api-key

2nd resource apply:
apiVersion: apimanagement.azure.com/v1api20220801
kind: Api
metadata:
  name: test-api-revision-1
  namespace: grandcentral
spec:
  apiRevision: "2"
  apiRevisionDescription: "test revision 2"
  description: API Testing for revsion 1
  apiType: http
  displayName: test-api-revision-1
  format: swagger-json
  isCurrent: false
  owner:
    armId: "/subscriptions/2e46XXXXXXXX7a52cd1/resourceGroups/rg-XXXX-compute-dev/providers/Microsoft.ApiManagement/service/apim-XXX-dev"
  protocols: 
    - https
  value: 
  path: test/v1/poc
  subscriptionKeyParameterNames:
    header: api-key


Screenshot:

![Image](https://github.com/user-attachments/assets/e9ccb3e3-1652-4049-8133-3010f4ab68a8)

**Comment by theunrepentantgeek** [comment]
I don't think the `ID` column in your screenshot is showing the `apiRevision` value; I think all that's showing is that you have exactly one revision.

Both of your YAML samples above have the same name and namespace:

``` yaml
metadata:
  name: test-api-revision-1
  namespace: abc
```

When you apply the second one, it will _overwrite_ the resource in the cluster, and ASO will then _update_ the Azure resource to match.

What happens when you use this as your second resource?

``` yaml
apiVersion: apimanagement.azure.com/v1api20220801
kind: Api
metadata:
  name: test-api-revision-2
  namespace: abc
spec:
  apiRevision: "2"
  apiRevisionDescription: "test revision 2"
  description: API Testing for revsion 2
  apiType: http
  displayName: test-api-revision-2
  format: swagger-json
  isCurrent: false
  owner:
    armId: "/subscriptions/2e46XXXXXXXX7a52cd1/resourceGroups/rg-XXXX-compute-dev/providers/Microsoft.ApiManagement/service/apim-XXX-dev"
  protocols: 
    - https
  value: 
  path: test/v1/poc
  subscriptionKeyParameterNames:
    header: api-key
```
