### ISSUE TITLE
Feature: Support config or secrets map reference for containerservice.azure.com identityProfile

### ISSUE THREAD

**Issue by jamie-oconnell** [Azure/azure-service-operator#4620]
https://azure.github.io/azure-service-operator/reference/containerservice/v1api20231001/#UserAssignedIdentity

Support referencing configmap or secret for clientId & objectId for user assigned identity for identityProfile on containerservice.

```yaml
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedCluster
metadata:
  name: example
  namespace: default
spec:
  location: westus3
  owner:
    name: aso-sample-rg
  identityProfile:
     principalIdFromConfig:
        name: identity-settings
        key: principalId
     clientIdFromConfig:
        name: identity-settings
        key: clientId
```
