### ISSUE TITLE
Bug: unable to create user with permissions on PostgreSQL 16+

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-service-operator#4639]
## Describe the bug

Unable to create a user in PostgreSQL on versions 16+ with custom [predefined role(s)](https://www.postgresql.org/docs/16/predefined-roles.html), e.g. `pg_read_all_data`, `pg_write_all_data`)

Azure Service Operator Version: v2.12.0

User object status:
```yaml
status:
  conditions:
    - lastTransitionTime: '2025-03-18T12:35:22Z'
      message: >-
        ensuring server roles: ERROR: permission denied to grant role
        "pg_write_all_data" (SQLSTATE 42501)
      observedGeneration: 1
      reason: Failed
      severity: Warning
      status: 'False'
      type: Ready
```

PostgreSQL Logs:
```txt
2025-03-18 12:48:25 UTC-67d96b99.c60-ERROR:  permission denied to grant role \"pg_write_all_data\"","detail": "Only roles with the ADMIN option on role \"pg_write_all_data\" may grant this role.","statement": "GRANT pg_write_all_data TO \"sampleuser\"

```

## Expected behavior

User successfully created like before on versions 14/15.

## To Reproduce

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: samplepostgresql
  namespace: default
type: Opaque
data:
  password: hErEiSMyaWesOMEpassw0rd
---
apiVersion: v1
kind: Secret
metadata:
  name: sampleuser
  namespace: default
type: Opaque
data:
  password: hErEiSMyn0tSOaWesOMEpassw0rd
---
apiVersion: dbforpostgresql.azure.com/v1api20221201
kind: FlexibleServer
metadata:
  name: samplepostgresql
  namespace: default
spec:
  location: eastus
  owner:
    name: aso-sample-rg
  version: "16"
  sku:
    name: Standard_D4s_v3
    tier: GeneralPurpose
  administratorLogin: myAdmin
  administratorLoginPassword: # This is the name/key of a Kubernetes secret in the same namespace
    name: samplepostgresql
    key: password
  storage:
    storageSizeGB: 32
---
apiVersion: dbforpostgresql.azure.com/v1
kind: User
metadata:
  name: sampleuser
  namespace: default
spec:
  owner:
    name: samplepostgresql
  roles:
    - pg_write_all_data
  roleOptions:
    login: true
    createRole: true
  localUser:
    serverAdminUsername: myAdmin
    serverAdminPassword:
      name: samplepostgresql
      key: password
    password:
      name: sampleuser
      key: password

```

## Additional context

There were some permission related changes in [PostgreSQL 16](https://www.postgresql.org/docs/16/release-16.html) release
