### ISSUE TITLE
Feature: Allow Injection of Hostname to Frontdoor Origins

### ISSUE THREAD

**Issue by karljaxon** [Azure/azure-service-operator#4641]
We're creating azure frontdoor origins using the AfdOrigin resource using the cdn.azure.com/v1api20230501 api, from here: https://azure.github.io/azure-service-operator/reference/cdn/

The actual origin is a private link, also made through ASO. The origin has a mandatory 'hostname' param, which we set to the alias of the privatelink. The alias is based on the name, but not predictable. But the operatorSpec of the private link is exported, so we have a clear value to use. I'd like to be able to take this output and import it as the hostname of the origin, in much the same way that role assignments can import a pricipalIdFromConfig.

I would quite like the attached code below work. It's all there apart from the 'hostNameFromConfig'. 

```
apiVersion: cdn.azure.com/v1api20230501
kind: AfdOrigin
metadata:
  name: my-origin
spec:
  owner:
    name: my-origingroup
  hostNameFromConfig:
    name: my-privatelink
    key: alias
  sharedPrivateLinkResource:
    requestMessage: "Please approve this connection"
    privateLinkLocation: usw3
    privateLink:
      reference: 
        group: network.azure.com
        kind: PrivateLinkService
        name: my-link
---
apiVersion: network.azure.com/v1api20240301
kind: PrivateLinkService
metadata:
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
  name: my-link
spec:
  location: usw3
  owner:
    name: my-rg
  operatorSpec:
    configMaps:
      alias:
        name: my-privatelink
        key: alias
```
