### ISSUE TITLE
Bug: Another operation is pending on the specified resource ERROR CODE: Conflict

### ISSUE THREAD

**Issue by vronnG-dw** [Azure/azure-service-operator#4650]
## Describe the bug
- Resource ready status fails with the below error and doesn't resolve on retry.
- So far noticing this with `dnsResolvers` `DnsResolversInboundEndpoint` & `DnsResolversOutboundEndpoint`
- No other resources are reporting unhealthy accept one.
  - but we have noticed that sometimes two resources `DnsResolversInboundEndpoint` and `dnsResolvers` fails together on conflicts too. 
- Couldn't find anything on the controller logs about whats blocking this GET request

### Manifest:
```
apiVersion: network.azure.com/v1api20220701
kind: DnsResolversInboundEndpoint
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '40'
  name: dnsin-name
  namespace: test
spec:
  ipConfigurations:
    - privateIpAddress: 10.xx.xx.xx
      privateIpAllocationMethod: Static
      subnet:
        reference:
          group: network.azure.com
          kind: VirtualNetworksSubnet
          name: snet-name
  location: westus3
  owner:
    armId: >-
      /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/dnsResolvers/dnspr-name
```

```
$kubectl get dnsResolvers
NAME                              READY   SEVERITY   REASON      MESSAGE
dnspr-shared-bonzai-dev-westus3   True               Succeeded   


$kubectl get DnsResolversInboundEndpoint
NAME                              READY   SEVERITY   REASON     MESSAGE
dnsin-shared-bonzai-dev-westus3   False   Error      Conflict   Another operation is pending on the specified resource.: GET https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/locations/westus3/dnsResolverOperationStatuses/aaaaa==...
```

### ERROR
```
      message: >
        Another operation is pending on the specified resource.: GET
        https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/locations/westus3/dnsResolverOperationStatuses/aaaaa==

        --------------------------------------------------------------------------------

        RESPONSE 200: 200 OK

        ERROR CODE: Conflict

        --------------------------------------------------------------------------------

        {
          "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/locations/westus3/dnsResolverOperationStatuses/aaaaa==",
          "name": "aaaaa==",
          "startTime": "2025-03-26T10:39:05.0000000Z",
          "endTime": "2025-03-26T10:39:08.0000000Z",
          "status": "Failed",
          "error": {
            "details": null,
            "code": "Conflict",
            "message": "Another operation is pending on the specified resource.",
            "target": null
          }
        }

        --------------------------------------------------------------------------------
      observedGeneration: 2
      reason: Conflict
      severity: Error
      status: 'False'
```

```
kubectl get deployment -o wide
NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                                                          SELECTOR
azureserviceoperator-controller-manager   2/2     2            2           14d   manager      docker-mcr.xx.xx.net/k8s/azureserviceoperator:v2.12.0   control-plane=controller-manager
```
