### ISSUE TITLE
Bug: SignalR Replica mandatory field is marked as optional

### ISSUE THREAD

**Issue by AndreiBarbuOz** [Azure/azure-service-operator#4672]
## Describe the bug

The SKU is mandatory for SignalR replicas:

https://github.com/Azure/azure-service-operator/blob/ba00156bcd685ee73f96bcf8ad3ca73d3e5e329d/v2/api/signalrservice/v1api20240301/replica_types_gen.go#L280-L281

Azure Service Operator Version: v2.12.0

## Expected behavior

Replica objects should not be accepted by the API server if they are invalid

```
Unhandled Exception in Azure SignalR service. Please try again later.: PUT https://management.azure.com/subscriptions/000000000000000/resourceGroups/local-we-rg/providers/Microsoft.SignalRService/signalR/local-we-signalr/replicas/local-we-signalr-we 
 -replica                                                                                                                                                                                                                                                                             
       --------------------------------------------------------------------------------                                                                                                                                                                                               
       RESPONSE 500: 500 Internal Server Error                                                                                                                                                                                                                                        
       ERROR CODE: InternalServerError                                                                                                                                                                                                                                                
       --------------------------------------------------------------------------------                                                                                                                                                                                               
       {                                                                                                                                                                                                                                                                              
         "error": {                                                                                                                                                                                                                                                                   
           "code": "InternalServerError",                                                                                                                                                                                                                                             
           "message": "Unhandled Exception in Azure SignalR service. Please try again later."                                                                                                                                                                                         
         }                                                                                                                                                                                                                                                                            
       }                                                                                                                                                                                                                                                                              
       -------------------------------------------------------------------------------- 
```

## To Reproduce

```
apiVersion: signalrservice.azure.com/v1api20240301
kind: Replica
metadata:
  name: local-we-signalr-we-replica
  namespace: local
spec:
  azureName: local-we-signalr-we-replica
  location: westeurope
  owner:
    name: local-we-signalr
#  sku:
#    name: Premium_P1
---
apiVersion: signalrservice.azure.com/v1api20211001
kind: SignalR
metadata:
  name: local-we-signalr
  namespace: local
spec:
  azureName: local-we-signalr
  features:
  - flag: EnableConnectivityLogs
    value: "true"
  identity:
    type: SystemAssigned
  location: westus2
  owner:
    name: local-we-rg
  sku:
    capacity: 1
    name: Premium_P1
    tier: Premium
```
