### ISSUE TITLE
Kusto Database resource can't be deployed with armId owner

### ISSUE THREAD

**Issue by nikoraes** [Azure/azure-service-operator#4712]
## Describe the current behavior

The Kusto Database resource can only be deployed if the cluster is also managed by ASO. Using an armId as an owner is currently not supported.

The following fails to deploy:

```yaml
apiVersion: kusto.azure.com/v1api20230815
kind: Database
metadata:
  annotations:
    serviceoperator.azure.com/reconcile-policy: "detach-on-delete"
  name: {{ $kustoDatabaseName }}
spec:
  owner:
    armId: {{ $kustoClusterId }}
```

## Describe the improvement

Allow the cluster owner for a Database resource to be defined with an armId.

## Additional context

I get the following error message: `cannot run on unknown resource type <nil>, expected owner to be *kusto.Cluster`.

My guess is that it's coming from [database_extensions.go](https://github.com/Azure/azure-service-operator/blob/main/v2/api/kusto/customizations/database_extensions.go) on L42.

```go
	cluster, ok := owner.(*kusto.Cluster)
	if !ok {
		return extensions.PreReconcileCheckResult{},
			eris.Errorf("cannot run on unknown resource type %T, expected owner to be *kusto.Cluster", owner)
	}

```
