### ISSUE TITLE
Helm Chart: allow overriding Registry and Tag separately

### ISSUE THREAD

**Issue by eripa** [Azure/azure-service-operator#4746]
## Describe the current behavior

The Helm chart uses a single value to configure the Image repository + tag. While it technically works, it makes it cumbersome to setup patterns such as using an alternative image **registry** (mirror, pull through caches etc) while still relying on the Chart-provided image **tag**.

https://github.com/Azure/azure-service-operator/blob/dd05bc30bc24ba68b96fd57c3ab5c8912513df96/v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml#L202

## Describe the improvement

The Chart should allow configuring the Registry and Tag separately. 

Something along the lines of 

**values.yaml**
```yaml
  image:
    repository: mcr.microsoft.com/k8s/azureserviceoperator
    tag: "" # defaults to Chart version
    imagePullPolicy: IfNotPresent
```

and in the template:
```yaml
image: {{.Values.image.repository}}:{{- default .Chart.AppVersion .Values.image.tag }}
```

## Additional context

N/A
