### ISSUE TITLE
Bug: Eventhub namespace status needs final update

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#520]
Eventhub Namespaces being deployed via the generic operator are being last updated when the namespace enters the "Created" state.

```
status:
  message: 'eventhub.NamespacesCreateOrUpdateFuture: asynchronous operation has not
    completed'
  provisioned: true
  provisioning: true
  state: Created
```

Which means the operation isn't completed when the operator claims it is.

Fix the Ensure method for the EventHubNamespace ARMClient so that the final reconciliation happens when the resource is in a "Succeeded" or "Active" state.
