### ISSUE TITLE
Bug: invalid resourceGroup name results in empty EventhubNamespace status

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#563]
EventhubNamespace controller properly handles missing ResourceGroup but not validation failures on resourcegroup Name

Validation errors should at minimum be captured in the Status.Message

```
apiVersion: azure.microsoft.com/v1alpha1
kind: EventhubNamespace
metadata:
  name: eventhubnamespace-sample-77
  namespace: default
spec:
  location: westus
  resourceGroup: ""
  properties: {}
  sku:
    capacity: 1
    name: Standard
    tier: Standard
status: {}
```
