### ISSUE TITLE
Bug: PostgreSQL: update status.Message on success

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#587]
**Describe the bug**
Deployed a PSQL server and when it was done provisioning I checked the status subresource:

```
status:
  completed: "2020-01-22T18:43:34Z"
  message: 'postgresql.ServersCreateFuture: asynchronous operation has not completed'
  provisioned: true
  requested: "2020-01-22T18:39:42Z"
  state: Ready
```

Message needs to be updated to the standard success message for provisioned resources.

We use "resourcemanager.SuccessMsg" constant for this like in the below line.
https://github.com/Azure/azure-service-operator/blob/761440088072c08d378127af0eda00604834fa80/pkg/resourcemanager/psql/server/client.go#L210

This will need to be set in all paths in Ensure that return true,nil

https://github.com/Azure/azure-service-operator/blob/761440088072c08d378127af0eda00604834fa80/pkg/resourcemanager/psql/server/client.go#L118
