### ISSUE TITLE
Bug: Storage Operator Provisioning Incorrect Message of 'AlreadyExists'

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#908]
**Describe the bug**
The storage operator incorrectly displays an error of `Already Exists` when it is in the provisioning state. It goes away once the operator is successfully provisioned. 

**To Reproduce**
- Create a storage account instance
- Immediately do a Get 
- Check the status.Message field - should see `AlreadyExists`

Once the storage account successfully provisions, the message changes to `successfully provisioned`

**From the YAML:**
_Provisioning Status_
```
status:
  message: AlreadyExists
  provisioning: true
  requested: "2020-04-09T16:13:16Z"
  state: ResolvingDns
```

_Provisioned Status:_
```
status:
  message: successfully provisioned
  provisioned: true
  resourceId: /subscriptions/7060bca0-7a3c-44bd-b54c-4bb1e9facfac/resourceGroups/resourcegroup-azure-operators-mel/providers/Microsoft.Storage/storageAccounts/storageaccountsample888
  specHash: b99774201654795d4fed206d6f01cbb2723b28a0e5057c0ed1d1b64aac000ab8
  state: Succeeded
```

**Expected behavior**
Remove AlreadyExists when a Storage Account is provisioning from the message state.

**Screenshots**

**Additional context**
